/**
 * Script para actualizar o crm-db.json com os dados reais das propostas
 * com datas correctas (dataEnvio) para funcionar no Comparativo Semanal
 */
const fs = require('fs');
const path = require('path');

const DB_PATH = path.join(__dirname, 'crm-db.json');

// Ler o crm-db.json actual
const db = JSON.parse(fs.readFileSync(DB_PATH, 'utf-8'));

// Todos os deals com dataEnvio correcta
const initialDeals = [
  // ====== SEMANA ANTERIOR: 07-11 Jul 2026 ======
  { id: "d_sa_1", semana: "Semana Anterior", clienteNome: "IMOCASAIS", titulo: "Fornecimento de Blocos de nota, canetas Flyers", valor: 1385100, valorAprovado: 0, valorPerdido: 0, etapa: "negociacao", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Normal", diasAberto: 14, probabilidade: "40%", proximaAcao: "Entregar em contacto com o cliente para saber o orçamento deles", proximoContacto: "13/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "B", crmStatus: "Aberto", dataEnvio: "09/07/2026" },
  { id: "d_sa_2", semana: "Semana Anterior", clienteNome: "SUEZ", titulo: "Fornecimento de Flyers monofolha e tripticos", valor: 6260880, valorAprovado: 0, valorPerdido: 0, etapa: "negociacao", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Alta", diasAberto: 16, probabilidade: "80%", proximaAcao: "negociar a modalidade de pagamento", proximoContacto: "13/07/2026", observacoes: "Falta o envio da PO", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "07/07/2026" },
  { id: "d_sa_3", semana: "Semana Anterior", clienteNome: "TEIXEIRA DUARTE", titulo: "Fornecimento de Diversos", valor: 758100, valorAprovado: 758100, valorPerdido: 0, etapa: "fechado", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Alta", diasAberto: 17, probabilidade: "100%", proximaAcao: "Aumentar o fluxo de trabalhos com este cliente", proximoContacto: "13/07/2026", observacoes: "As artes já foram aprovadas", classeCliente: "A", crmStatus: "Fechado ganho", dataEnvio: "06/07/2026", dataAprovacao: "09/07/2026" },
  { id: "d_sa_4", semana: "Semana Anterior", clienteNome: "SIAC", titulo: "Fornecimento de brindes e merchandising", valor: 19418760, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Média", diasAberto: 16, probabilidade: "40%", proximaAcao: "Agendar uma reunião com o cliente", proximoContacto: "13/07/2026", observacoes: "Proposta remetida para validação", classeCliente: "A", crmStatus: "Aberto", dataEnvio: "07/07/2026" },
  { id: "d_sa_5", semana: "Semana Anterior", clienteNome: "ALIANÇA SEGUROS", titulo: "Fornecimento de Flyers dipticos", valor: 3328800, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Normal", diasAberto: 15, probabilidade: "40%", proximaAcao: "Considerar a possibilidade de apresentar um desconto", proximoContacto: "13/07/2026", observacoes: "Proposta remetida para validação", classeCliente: "A", crmStatus: "Aberto", dataEnvio: "08/07/2026" },
  { id: "d_sa_6", semana: "Semana Anterior", clienteNome: "COSCAL", titulo: "Fornecimento de flyers Tripticos", valor: 259350, valorAprovado: 259350, valorPerdido: 0, etapa: "producao", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Alta", diasAberto: 14, probabilidade: "100%", proximaAcao: "Conseguir o contacto do cliente final", proximoContacto: "13/07/2026", observacoes: "Material produzido e entregue", classeCliente: "A", crmStatus: "Aberto", dataEnvio: "09/07/2026", dataAprovacao: "10/07/2026" },
  { id: "d_sa_7", semana: "Semana Anterior", clienteNome: "ENDIAMA", titulo: "Fornecimento de materiais para outubro rosa", valor: 6958560, valorAprovado: 0, valorPerdido: 0, etapa: "negociacao", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Alta", diasAberto: 37, probabilidade: "80%", proximaAcao: "negociar a modalidade de pagamento", proximoContacto: "13/07/2026", observacoes: "Falta o envio da PO", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "16/06/2026" },
  { id: "d_sa_8", semana: "Semana Anterior", clienteNome: "PAY4ALL", titulo: "Fornecimento de Brindes para a filda", valor: 2106150, valorAprovado: 2106150, valorPerdido: 0, etapa: "fechado", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Alta", diasAberto: 28, probabilidade: "100%", proximaAcao: "Acompanhar o processo de produção", proximoContacto: "13/07/2026", observacoes: "Avaliação e criação de artes finais para produção", classeCliente: "C", crmStatus: "Fechado ganho", dataEnvio: "25/06/2026", dataAprovacao: "08/07/2026" },
  { id: "d_sa_9", semana: "Semana Anterior", clienteNome: "XPRINT", titulo: "Fornecimento de Brindes e Têxtil", valor: 2350680, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Normal", diasAberto: 17, probabilidade: "40%", proximaAcao: "Considerar a possibilidade de apresentar um desconto", proximoContacto: "13/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "B", crmStatus: "Aberto", dataEnvio: "06/07/2026" },
  { id: "d_sa_10", semana: "Semana Anterior", clienteNome: "DUBAI INVESTMENTS", titulo: "Fornecimento de Brindes", valor: 6156000, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Média", diasAberto: 13, probabilidade: "50%", proximaAcao: "Apresentar amostras Físicas", proximoContacto: "13/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "10/07/2026" },
  { id: "d_sa_11", semana: "Semana Anterior", clienteNome: "DUBAI INVESTMENTS", titulo: "Fornecimento de Flyrs", valor: 3249000, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Normal", diasAberto: 15, probabilidade: "40%", proximaAcao: "Apresentar amostras Físicas", proximoContacto: "13/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "08/07/2026" },
  { id: "d_sa_12", semana: "Semana Anterior", clienteNome: "BCGA", titulo: "Fornecimento de Lenços e gravatas", valor: 9095000, valorAprovado: 0, valorPerdido: 9095000, etapa: "perdido", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Média", diasAberto: 17, probabilidade: "0%", proximaAcao: "Apresentação de disponibilidade para futuros projectos", proximoContacto: "13/07/2026", observacoes: "Proposta rejeitada por causa do tempo de produção", classeCliente: "C", crmStatus: "Fechado perdido", dataEnvio: "06/07/2026", dataPerda: "10/07/2026" },
  { id: "d_sa_13", semana: "Semana Anterior", clienteNome: "BCGA", titulo: "Fornecimento de Fita Tulyy", valor: 2684700, valorAprovado: 0, valorPerdido: 2684700, etapa: "perdido", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Normal", diasAberto: 20, probabilidade: "0%", proximaAcao: "Apresentação de disponibilidade para futuros projectos", proximoContacto: "13/07/2026", observacoes: "Proposta reajustada por falta de amostras físicas", classeCliente: "A", crmStatus: "Fechado perdido", dataEnvio: "03/07/2026", dataPerda: "10/07/2026" },
  { id: "d_sa_14", semana: "Semana Anterior", clienteNome: "NOSSA SEGUROS", titulo: "Fornecimento de Material para filda", valor: 2809820, valorAprovado: 2809820, valorPerdido: 0, etapa: "fechado", comercialId: "u5", comercialNome: "Marta de Oliveira", prioridade: "Alta", diasAberto: 16, probabilidade: "100%", proximaAcao: "Dar inicio ao processo de produção", proximoContacto: "13/07/2026", observacoes: "Acompanhar o processo até ao fecho", classeCliente: "A", crmStatus: "Fechado ganho", dataEnvio: "07/07/2026", dataAprovacao: "09/07/2026" },
  { id: "d_sa_15", semana: "Semana Anterior", clienteNome: "ATO", titulo: "Fornecimento de brindes para Filda", valor: 7695000, valorAprovado: 7695000, valorPerdido: 0, etapa: "fechado", comercialId: "u5", comercialNome: "Marta de Oliveira", prioridade: "Alta", diasAberto: 17, probabilidade: "100%", proximaAcao: "Dar inicio ao processo de produção", proximoContacto: "13/07/2026", observacoes: "Acompanhar o processo até ao fecho", classeCliente: "C", crmStatus: "Fechado ganho", dataEnvio: "06/07/2026", dataAprovacao: "08/07/2026" },
  { id: "d_sa_16", semana: "Semana Anterior", clienteNome: "AFRICANA", titulo: "Fornecimento de material de letras monobloco", valor: 12398174.88, valorAprovado: 0, valorPerdido: 0, etapa: "negociacao", comercialId: "u5", comercialNome: "Marta de Oliveira", prioridade: "Média", diasAberto: 14, probabilidade: "50%", proximaAcao: "Acompanhamento do Processo até o fecho", proximoContacto: "13/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "B", crmStatus: "Aberto", dataEnvio: "09/07/2026" },
  { id: "d_sa_17", semana: "Semana Anterior", clienteNome: "DISBRA", titulo: "Fornecimento de sacolas e folhetos", valor: 222300, valorAprovado: 222300, valorPerdido: 0, etapa: "fechado", comercialId: "u5", comercialNome: "Marta de Oliveira", prioridade: "Alta", diasAberto: 16, probabilidade: "100%", proximaAcao: "Pressionar o envio das artes", proximoContacto: "13/07/2026", observacoes: "No aguardo das artes para produção", classeCliente: "B", crmStatus: "Fechado ganho", dataEnvio: "07/07/2026", dataAprovacao: "09/07/2026" },
  { id: "d_sa_18", semana: "Semana Anterior", clienteNome: "PRODEL", titulo: "Fornecimento de Tapetes", valor: 28581282, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u4", comercialNome: "José Neto", prioridade: "Média", diasAberto: 16, probabilidade: "50%", proximaAcao: "Negociar com o cliente", proximoContacto: "13/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "07/07/2026" },
  { id: "d_sa_19", semana: "Semana Anterior", clienteNome: "JUMUCUZA", titulo: "Fornecimento de protectores auditivos", valor: 953610, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u4", comercialNome: "José Neto", prioridade: "Normal", diasAberto: 15, probabilidade: "40%", proximaAcao: "Solicitar o ponto de situação da proposta", proximoContacto: "13/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "08/07/2026" },
  { id: "d_sa_20", semana: "Semana Anterior", clienteNome: "CERTAVE", titulo: "Fornecimento de sinaletica", valor: 1997394, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u4", comercialNome: "José Neto", prioridade: "Normal", diasAberto: 13, probabilidade: "40%", proximaAcao: "Monitorizar o processo de adjudicação", proximoContacto: "13/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "10/07/2026" },
  { id: "d_sa_21", semana: "Semana Anterior", clienteNome: "DP-WORLD", titulo: "Fornecimento de Brindes", valor: 3024990, valorAprovado: 3024990, valorPerdido: 0, etapa: "fechado", comercialId: "u2", comercialNome: "David Guedes", prioridade: "Alta", diasAberto: 15, probabilidade: "100%", proximaAcao: "Aguardar pelo envio das artes", proximoContacto: "13/07/2026", observacoes: "Entrega prevista para o dia 13", classeCliente: "C", crmStatus: "Fechado ganho", dataEnvio: "08/07/2026", dataAprovacao: "10/07/2026" },
  { id: "d_sa_22", semana: "Semana Anterior", clienteNome: "RHUANITO", titulo: "Fornecimento de Flyres e têxtil", valor: 687420, valorAprovado: 0, valorPerdido: 0, etapa: "negociacao", comercialId: "u2", comercialNome: "David Guedes", prioridade: "Alta", diasAberto: 13, probabilidade: "80%", proximaAcao: "Solicitar o ponto de situação", proximoContacto: "13/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "10/07/2026" },
  { id: "d_sa_23", semana: "Semana Anterior", clienteNome: "KERO", titulo: "Fornecimento de Brindes", valor: 221160, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u2", comercialNome: "David Guedes", prioridade: "Normal", diasAberto: 13, probabilidade: "40%", proximaAcao: "Solicitar o ponto de situação", proximoContacto: "13/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "10/07/2026" },
  { id: "d_sa_24", semana: "Semana Anterior", clienteNome: "ACQUA GLOBAL", titulo: "Fornecimento de pins", valor: 2109000, valorAprovado: 2109000, valorPerdido: 0, etapa: "fechado", comercialId: "u6", comercialNome: "Ilídio Pedro", prioridade: "Alta", diasAberto: 16, probabilidade: "100%", proximaAcao: "Dar inicio ao processo de produção", proximoContacto: "13/07/2026", observacoes: "Acompanhar o processo até ao fecho", classeCliente: "C", crmStatus: "Fechado ganho", dataEnvio: "07/07/2026", dataAprovacao: "09/07/2026" },
  { id: "d_sa_25", semana: "Semana Anterior", clienteNome: "OMATAPALO", titulo: "Fornecimento De Placas sinaleticas", valor: 21909090, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u6", comercialNome: "Ilídio Pedro", prioridade: "Média", diasAberto: 17, probabilidade: "20%", proximaAcao: "Solicitar o ponto de situação", proximoContacto: "13/07/2026", observacoes: "O cliente não respondeu ao nosso e-mail", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "06/07/2026" },
  { id: "d_sa_26", semana: "Semana Anterior", clienteNome: "PURIGLASS", titulo: "Fornecimento de T-shirts, autocolantes cartão de visita", valor: 706800, valorAprovado: 706800, valorPerdido: 0, etapa: "fechado", comercialId: "u3", comercialNome: "Fernando Leite", prioridade: "Alta", diasAberto: 15, probabilidade: "100%", proximaAcao: "Entregar o material ao cliente", proximoContacto: "13/07/2026", observacoes: "Acompanhar o processo até ao fecho", classeCliente: "C", crmStatus: "Fechado ganho", dataEnvio: "08/07/2026", dataAprovacao: "10/07/2026" },
  { id: "d_sa_27", semana: "Semana Anterior", clienteNome: "5 LINHAS", titulo: "Fornecimento de diversos", valor: 8468775, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u3", comercialNome: "Fernando Leite", prioridade: "Média", diasAberto: 13, probabilidade: "40%", proximaAcao: "Solicitar o ponto de situação", proximoContacto: "13/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "B", crmStatus: "Aberto", dataEnvio: "10/07/2026" },
  { id: "d_sa_28", semana: "Semana Anterior", clienteNome: "SAAS SISTEMAS TECNOLOGIAS", titulo: "Fornecimento de passes", valor: 29640, valorAprovado: 29640, valorPerdido: 0, etapa: "fechado", comercialId: "u3", comercialNome: "Fernando Leite", prioridade: "Alta", diasAberto: 13, probabilidade: "100%", proximaAcao: "Entregar o material ao cliente", proximoContacto: "13/07/2026", observacoes: "Acompanhar o processo até ao fecho", classeCliente: "C", crmStatus: "Fechado ganho", dataEnvio: "10/07/2026", dataAprovacao: "11/07/2026" },
  { id: "d_sa_29", semana: "Semana Anterior", clienteNome: "GRUPO CAJUEIRO", titulo: "Fornecimento de cartões de visitas", valor: 193800, valorAprovado: 193800, valorPerdido: 0, etapa: "fechado", comercialId: "u3", comercialNome: "Fernando Leite", prioridade: "Alta", diasAberto: 18, probabilidade: "100%", proximaAcao: "Entregar o material ao cliente", proximoContacto: "13/07/2026", observacoes: "Acompanhar o processo até ao fecho", classeCliente: "C", crmStatus: "Fechado ganho", dataEnvio: "05/07/2026", dataAprovacao: "08/07/2026" },
  { id: "d_sa_30", semana: "Semana Anterior", clienteNome: "PEDRA PRECIOSA", titulo: "Fornecimento de toalhas bordadas", valor: 251370, valorAprovado: 0, valorPerdido: 0, etapa: "negociacao", comercialId: "u3", comercialNome: "Fernando Leite", prioridade: "Média", diasAberto: 16, probabilidade: "60%", proximaAcao: "Solicitar o ponto de situação", proximoContacto: "13/07/2026", observacoes: "Aguardando a confirmação do cliente", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "07/07/2026" },
  { id: "d_sa_31", semana: "Semana Anterior", clienteNome: "BAXTTER", titulo: "Fornecimento de brindes e flyres", valor: 1657560, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u3", comercialNome: "Fernando Leite", prioridade: "Normal", diasAberto: 13, probabilidade: "40%", proximaAcao: "Solicitar o ponto de situação", proximoContacto: "13/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "10/07/2026" },
  
  // ====== SEMANA FINDA: 13-17 Jul 2026 ======
  { id: "d_sf_32", semana: "Semana Finda", clienteNome: "UNITEL", titulo: "Canecas de Porcelana e Garrafas Térmica", valor: 96124800, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Alta", diasAberto: 10, probabilidade: "40%", proximaAcao: "Incentivar o cliente para o envio da contraproposta", proximoContacto: "20/07/2026", observacoes: "O processo de análise das propostas está em curso", classeCliente: "A", crmStatus: "Aberto", dataEnvio: "13/07/2026" },
  { id: "d_sf_33", semana: "Semana Finda", clienteNome: "FINSTAR/ZAP", titulo: "Sacos TNT Personalizados", valor: 1687200, valorAprovado: 1687200, valorPerdido: 0, etapa: "fechado", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Média", diasAberto: 8, probabilidade: "100%", proximaAcao: "Pressionar a adjudicação da proposta das T-Shirts", proximoContacto: "20/07/2026", observacoes: "Já entregamos 300 unidades", classeCliente: "A", crmStatus: "Fechado ganho", dataEnvio: "15/07/2026", dataAprovacao: "16/07/2026" },
  { id: "d_sf_34", semana: "Semana Finda", clienteNome: "FINSTAR/ZAP", titulo: "T-Shirts para Lojistas", valor: 21161250, valorAprovado: 0, valorPerdido: 0, etapa: "negociacao", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Alta", diasAberto: 9, probabilidade: "60%", proximaAcao: "Solicitar o ponto de situação da PO", proximoContacto: "20/07/2026", observacoes: "Aguardamos a formalização da adjudicação", classeCliente: "A", crmStatus: "Aberto", dataEnvio: "14/07/2026" },
  { id: "d_sf_35", semana: "Semana Finda", clienteNome: "CARPINANGOLA/CASAIS", titulo: "Bloco de Notas e Canetas", valor: 2017800, valorAprovado: 2017800, valorPerdido: 0, etapa: "fechado", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Alta", diasAberto: 8, probabilidade: "100%", proximaAcao: "Alinhamento com a cliente para obter mais trabalhos", proximoContacto: "20/07/2026", observacoes: "O processo de produção está em curso", classeCliente: "B", crmStatus: "Fechado ganho", dataEnvio: "15/07/2026", dataAprovacao: "16/07/2026" },
  { id: "d_sf_36", semana: "Semana Finda", clienteNome: "CEGID/PRIMAVERA", titulo: "Impressão de Flyers", valor: 445700, valorAprovado: 445700, valorPerdido: 0, etapa: "fechado", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Alta", diasAberto: 6, probabilidade: "100%", proximaAcao: "Cumprimento do prazo de entrega", proximoContacto: "20/07/2026", observacoes: "O processo de produção está em curso", classeCliente: "B", crmStatus: "Fechado ganho", dataEnvio: "17/07/2026", dataAprovacao: "17/07/2026" },
  { id: "d_sf_37", semana: "Semana Finda", clienteNome: "FINSTAR/ZAP", titulo: "T-Shirts para Filda", valor: 1966500, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Normal", diasAberto: 6, probabilidade: "50%", proximaAcao: "Persuadir a aprovação usando o prazo de entrega", proximoContacto: "20/07/2026", observacoes: "As propostas ainda estão a ser analisadas", classeCliente: "A", crmStatus: "Aberto", dataEnvio: "17/07/2026" },
  { id: "d_sf_38", semana: "Semana Finda", clienteNome: "SIAC", titulo: "Totens em Betão", valor: 29641900, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Normal", diasAberto: 7, probabilidade: "40%", proximaAcao: "Solicitar uma reunião com este cliente", proximoContacto: "20/07/2026", observacoes: "A nossa proposta foi submetida para avaliação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "16/07/2026" },
  { id: "d_sf_39", semana: "Semana Finda", clienteNome: "SBM OFFSHORE", titulo: "Impressão de Autocolante", valor: 339150, valorAprovado: 339150, valorPerdido: 0, etapa: "fechado", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Normal", diasAberto: 44, probabilidade: "100%", proximaAcao: "Entrega do material ao cliente", proximoContacto: "20/07/2026", observacoes: "O material está pronto para ser entregue", classeCliente: "A", crmStatus: "Fechado ganho", dataEnvio: "09/06/2026", dataAprovacao: "15/07/2026" },
  { id: "d_sf_40", semana: "Semana Finda", clienteNome: "BCGA", titulo: "Fornecimento de Sacolas", valor: 3135000, valorAprovado: 3135000, valorPerdido: 0, etapa: "fechado", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Alta", diasAberto: 10, probabilidade: "100%", proximaAcao: "Levantar o material do cliente no fornecedor", proximoContacto: "20/07/2026", observacoes: "Material em produção no fornecedor", classeCliente: "A", crmStatus: "Fechado ganho", dataEnvio: "13/07/2026", dataAprovacao: "14/07/2026" },
  { id: "d_sf_41", semana: "Semana Finda", clienteNome: "TREVOTECH", titulo: "Fornecimento de Polos", valor: 889200, valorAprovado: 889200, valorPerdido: 0, etapa: "fechado", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Normal", diasAberto: 10, probabilidade: "100%", proximaAcao: "Solicitar feedback do material entregue", proximoContacto: "20/07/2026", observacoes: "Material produzido e entregue", classeCliente: "C", crmStatus: "Fechado ganho", dataEnvio: "13/07/2026", dataAprovacao: "15/07/2026" },
  { id: "d_sf_42", semana: "Semana Finda", clienteNome: "ANGOLACA", titulo: "Fornecimento de Materiais Diversos", valor: 14248432.5, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Média", diasAberto: 6, probabilidade: "50%", proximaAcao: "Contactar a cliente para agendar uma reunião", proximoContacto: "20/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "17/07/2026" },
  { id: "d_sf_43", semana: "Semana Finda", clienteNome: "DUBAI INVESTMENTS", titulo: "Fornecimento de Garrafas Térmicas", valor: 29724360, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Média", diasAberto: 9, probabilidade: "40%", proximaAcao: "Avaliar a possibilidade de dar um desconto", proximoContacto: "20/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "14/07/2026" },
  { id: "d_sf_44", semana: "Semana Finda", clienteNome: "FADA", titulo: "Fornecimento de Brindes", valor: 3583000, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Média", diasAberto: 6, probabilidade: "40%", proximaAcao: "Solicitar o ponto de situação", proximoContacto: "20/07/2026", observacoes: "Proposta remetida para avaliação", classeCliente: "B", crmStatus: "Aberto", dataEnvio: "17/07/2026" },
  { id: "d_sf_45", semana: "Semana Finda", clienteNome: "NOSSA SEGUROS", titulo: "Fornecimento de Material para Filda", valor: 2530550, valorAprovado: 2530550, valorPerdido: 0, etapa: "fechado", comercialId: "u5", comercialNome: "Marta de Oliveira", prioridade: "Alta", diasAberto: 7, probabilidade: "100%", proximaAcao: "Dar inicio ao processo de produção", proximoContacto: "20/07/2026", observacoes: "Acompanhamento até finalizar o processo", classeCliente: "B", crmStatus: "Fechado ganho", dataEnvio: "16/07/2026", dataAprovacao: "17/07/2026" },
  { id: "d_sf_46", semana: "Semana Finda", clienteNome: "PROGRAMA ALIMENTAR", titulo: "Fornecimento de Materiais Diversos", valor: 7060875, valorAprovado: 0, valorPerdido: 0, etapa: "negociacao", comercialId: "u5", comercialNome: "Marta de Oliveira", prioridade: "Normal", diasAberto: 6, probabilidade: "40%", proximaAcao: "Solicitar um feedback do orçamento", proximoContacto: "20/07/2026", observacoes: "A nossa proposta está em análise", classeCliente: "B", crmStatus: "Aberto", dataEnvio: "17/07/2026" },
  { id: "d_sf_47", semana: "Semana Finda", clienteNome: "DIVERSIFICA MAIS", titulo: "Fornecimento de Passes PVC e Fitas", valor: 422712, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u5", comercialNome: "Marta de Oliveira", prioridade: "Normal", diasAberto: 9, probabilidade: "40%", proximaAcao: "Solicitar um feedback do orçamento", proximoContacto: "20/07/2026", observacoes: "Apresentamos a proposta e aguardamos feedback", classeCliente: "B", crmStatus: "Aberto", dataEnvio: "14/07/2026" },
  { id: "d_sf_48", semana: "Semana Finda", clienteNome: "ATO", titulo: "Fornecimento e Montagem de Sinaléticas", valor: 1983600, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u5", comercialNome: "Marta de Oliveira", prioridade: "Normal", diasAberto: 7, probabilidade: "40%", proximaAcao: "Contactar o cliente para impulsionar a adjudicação", proximoContacto: "20/07/2026", observacoes: "A nossa proposta está em análise", classeCliente: "B", crmStatus: "Aberto", dataEnvio: "16/07/2026" },
  { id: "d_sf_49", semana: "Semana Finda", clienteNome: "VIAÇÃO E TRÂNSITO", titulo: "Flyers e Roll Ups", valor: 7296000, valorAprovado: 7296000, valorPerdido: 0, etapa: "fechado", comercialId: "u5", comercialNome: "Marta de Oliveira", prioridade: "Alta", diasAberto: 6, probabilidade: "100%", proximaAcao: "Solicitar o envio das artes para a produção", proximoContacto: "20/07/2026", observacoes: "As artes serão partilhadas na segunda-feira", classeCliente: "A", crmStatus: "Fechado ganho", dataEnvio: "17/07/2026", dataAprovacao: "17/07/2026" },
  { id: "d_sf_50", semana: "Semana Finda", clienteNome: "BANCO BNI", titulo: "Impressão de Flyers", valor: 881448, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u4", comercialNome: "José Neto", prioridade: "Normal", diasAberto: 10, probabilidade: "40%", proximaAcao: "Solicitar a contraproposta do cliente", proximoContacto: "20/07/2026", observacoes: "Não tivemos feedback da nossa proposta", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "13/07/2026" },
  
  // ====== SEMANA 27-31 Jul 2026 (dados do relatório Excel) ======
  { id: "d_w3_1", semana: "27-31 Jul 2026", clienteNome: "UNITEL", titulo: "Canecas de Porcelana e Garrafas Térmicas", valor: 96124800, valorAprovado: 0, valorPerdido: 0, etapa: "negociacao", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Alta", diasAberto: 17, probabilidade: "60%", proximaAcao: "Aguardar contraproposta", proximoContacto: "03/08/2026", observacoes: "Em análise", classeCliente: "A", crmStatus: "Aberto", dataEnvio: "27/07/2026" },
  { id: "d_w3_2", semana: "27-31 Jul 2026", clienteNome: "FINSTAR/ZAP", titulo: "T-Shirts para Lojistas", valor: 21161250, valorAprovado: 21161250, valorPerdido: 0, etapa: "fechado", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Alta", diasAberto: 16, probabilidade: "100%", proximaAcao: "Acompanhar produção", proximoContacto: "03/08/2026", observacoes: "Adjudicado", classeCliente: "A", crmStatus: "Fechado ganho", dataEnvio: "14/07/2026", dataAprovacao: "28/07/2026" },
  { id: "d_w3_3", semana: "27-31 Jul 2026", clienteNome: "SIAC", titulo: "Totens em Betão", valor: 29641900, valorAprovado: 0, valorPerdido: 0, etapa: "negociacao", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Normal", diasAberto: 14, probabilidade: "50%", proximaAcao: "Agendar reunião técnica", proximoContacto: "03/08/2026", observacoes: "Em negociação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "29/07/2026" },
  { id: "d_w3_4", semana: "27-31 Jul 2026", clienteNome: "BCGA", titulo: "Fornecimento de Sacolas TNT Extra", valor: 4250000, valorAprovado: 4250000, valorPerdido: 0, etapa: "fechado", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Alta", diasAberto: 8, probabilidade: "100%", proximaAcao: "Preparar entrega", proximoContacto: "03/08/2026", observacoes: "Aprovado", classeCliente: "A", crmStatus: "Fechado ganho", dataEnvio: "28/07/2026", dataAprovacao: "30/07/2026" },
  { id: "d_w3_5", semana: "27-31 Jul 2026", clienteNome: "DUBAI INVESTMENTS", titulo: "Garrafas Térmicas + Brindes Personalizados", valor: 29724360, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Média", diasAberto: 15, probabilidade: "40%", proximaAcao: "Follow-up", proximoContacto: "03/08/2026", observacoes: "Aguardamos resposta", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "27/07/2026" },
  { id: "d_w3_6", semana: "27-31 Jul 2026", clienteNome: "VIAÇÃO E TRÂNSITO", titulo: "Flyers Roll Ups Adicionais", valor: 3648000, valorAprovado: 3648000, valorPerdido: 0, etapa: "fechado", comercialId: "u5", comercialNome: "Marta de Oliveira", prioridade: "Alta", diasAberto: 7, probabilidade: "100%", proximaAcao: "Entregar material", proximoContacto: "03/08/2026", observacoes: "Aprovado e em produção", classeCliente: "A", crmStatus: "Fechado ganho", dataEnvio: "29/07/2026", dataAprovacao: "31/07/2026" },
  { id: "d_w3_7", semana: "27-31 Jul 2026", clienteNome: "PRODEL", titulo: "Tapetes Personalizados Adicionais", valor: 14500000, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u4", comercialNome: "José Neto", prioridade: "Média", diasAberto: 10, probabilidade: "40%", proximaAcao: "Aguardar decisão", proximoContacto: "03/08/2026", observacoes: "Em avaliação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "28/07/2026" },
  { id: "d_w3_8", semana: "27-31 Jul 2026", clienteNome: "DP-WORLD", titulo: "Brindes Corporativos Agosto", valor: 5124000, valorAprovado: 5124000, valorPerdido: 0, etapa: "fechado", comercialId: "u2", comercialNome: "David Guedes", prioridade: "Alta", diasAberto: 6, probabilidade: "100%", proximaAcao: "Iniciar produção", proximoContacto: "03/08/2026", observacoes: "Adjudicado", classeCliente: "C", crmStatus: "Fechado ganho", dataEnvio: "30/07/2026", dataAprovacao: "31/07/2026" },
  
  // ====== SEMANA ACTUAL: 04-08 Ago 2026 ======
  { id: "d_wa_1", semana: "04-08 Ago 2026", clienteNome: "UNITEL", titulo: "Follow-up Canecas de Porcelana", valor: 96124800, valorAprovado: 0, valorPerdido: 0, etapa: "negociacao", comercialId: "u15", comercialNome: "Luísa Baltazar", prioridade: "Alta", diasAberto: 24, probabilidade: "60%", proximaAcao: "Reunião com decisor", proximoContacto: "11/08/2026", observacoes: "Negociação activa", classeCliente: "A", crmStatus: "Aberto", dataEnvio: "04/08/2026" },
  { id: "d_wa_2", semana: "04-08 Ago 2026", clienteNome: "ANGOLACA", titulo: "Materiais Diversos Ago 2026", valor: 14248432.5, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u1", comercialNome: "Amélia Cassinda", prioridade: "Média", diasAberto: 13, probabilidade: "40%", proximaAcao: "Aguardar decisão", proximoContacto: "11/08/2026", observacoes: "Em avaliação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "05/08/2026" },
  { id: "d_wa_3", semana: "04-08 Ago 2026", clienteNome: "NOSSA SEGUROS", titulo: "Brindes Agosto 2026", valor: 3500000, valorAprovado: 3500000, valorPerdido: 0, etapa: "fechado", comercialId: "u5", comercialNome: "Marta de Oliveira", prioridade: "Alta", diasAberto: 5, probabilidade: "100%", proximaAcao: "Acompanhar produção", proximoContacto: "11/08/2026", observacoes: "Aprovado", classeCliente: "B", crmStatus: "Fechado ganho", dataEnvio: "04/08/2026", dataAprovacao: "06/08/2026" },
  { id: "d_wa_4", semana: "04-08 Ago 2026", clienteNome: "PRODEL", titulo: "Tapetes Grande Quantidade", valor: 28581282, valorAprovado: 0, valorPerdido: 0, etapa: "proposta", comercialId: "u4", comercialNome: "José Neto", prioridade: "Alta", diasAberto: 12, probabilidade: "50%", proximaAcao: "Reunião com cliente", proximoContacto: "11/08/2026", observacoes: "Aguardamos aprovação", classeCliente: "C", crmStatus: "Aberto", dataEnvio: "06/08/2026" },
  { id: "d_wa_5", semana: "04-08 Ago 2026", clienteNome: "KERO", titulo: "Brindes Promocionais", valor: 3800000, valorAprovado: 3800000, valorPerdido: 0, etapa: "fechado", comercialId: "u2", comercialNome: "David Guedes", prioridade: "Normal", diasAberto: 4, probabilidade: "100%", proximaAcao: "Iniciar produção", proximoContacto: "11/08/2026", observacoes: "Aprovado", classeCliente: "C", crmStatus: "Fechado ganho", dataEnvio: "07/08/2026", dataAprovacao: "08/08/2026" }
];

// Manter os deals existentes no DB que NÃO tenham IDs que colidem com os novos
const existingNonInitial = (db.deals || []).filter(d => 
  !d.id.startsWith('d_sa_') && 
  !d.id.startsWith('d_sf_') && 
  !d.id.startsWith('d_w3_') && 
  !d.id.startsWith('d_wa_')
);

// Combinar: initialDeals primeiro (com dataEnvio), depois os restantes existentes
db.deals = [...initialDeals, ...existingNonInitial];

console.log(`✅ Updated crm-db.json with ${initialDeals.length} initial deals + ${existingNonInitial.length} existing deals`);
console.log(`📊 Total deals: ${db.deals.length}`);

// Salvar
fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2), 'utf-8');
console.log('✅ crm-db.json saved successfully!');
