import { Usuario, Cliente, Visita, Deal, Guideline, NotificationItem, ActivityFeed } from "./types";

export const initialComerciais: Usuario[] = [
  {
    "id": "u15",
    "nome": "Luísa Baltazar",
    "email": "luisa.baltazar@gpaangola.co.ao",
    "perfil": "comercial",
    "funcao": "Comercial",
    "metaMensal": 30000000,
    "metaSemanal": 7500000,
    "comissao": 0.03,
    "pesoConversao": 0.4,
    "telefone": "928999888",
    "whatsappNumero": "928999888",
    "foto": "",
    "status": "ativo",
    "silencioso": false,
    "provincia": "Luanda",
    "senha": "gpa2026"
  },
  {
    "id": "u1",
    "nome": "Amélia Cassinda",
    "email": "amelia.cassinda@gpaangola.co.ao",
    "perfil": "comercial",
    "funcao": "Sênior",
    "metaMensal": 25000000,
    "metaSemanal": 6250000,
    "comissao": 0.03,
    "pesoConversao": 0.4,
    "telefone": "922111222",
    "whatsappNumero": "922111222",
    "foto": "",
    "status": "ativo",
    "silencioso": false,
    "provincia": "Luanda",
    "senha": "gpa2026"
  },
  {
    "id": "u5",
    "nome": "Marta Graça",
    "email": "marta.graca@gpaangola.co.ao",
    "perfil": "comercial",
    "funcao": "Sênior",
    "metaMensal": 25000000,
    "metaSemanal": 6250000,
    "comissao": 0.03,
    "pesoConversao": 0.4,
    "telefone": "926555666",
    "whatsappNumero": "926555666",
    "foto": "",
    "status": "ativo",
    "silencioso": false,
    "provincia": "Benguela",
    "senha": "gpa2026"
  },
  {
    "id": "u4",
    "nome": "José Neto",
    "email": "jose.neto@gpaangola.co.ao",
    "perfil": "comercial",
    "funcao": "Sênior",
    "metaMensal": 20000000,
    "metaSemanal": 5000000,
    "comissao": 0.03,
    "pesoConversao": 0.4,
    "telefone": "925444555",
    "whatsappNumero": "925444555",
    "foto": "",
    "status": "ativo",
    "silencioso": false,
    "provincia": "Luanda",
    "senha": "gpa2026"
  },
  {
    "id": "u2",
    "nome": "David Guedes",
    "email": "david.guedes@gpaangola.co.ao",
    "perfil": "comercial",
    "funcao": "Comercial",
    "metaMensal": 15000000,
    "metaSemanal": 3750000,
    "comissao": 0.03,
    "pesoConversao": 0.4,
    "telefone": "923222333",
    "whatsappNumero": "923222333",
    "foto": "",
    "status": "ativo",
    "silencioso": false,
    "provincia": "Cabinda",
    "senha": "gpa2026"
  },
  {
    "id": "u6",
    "nome": "Ilídio Pedro",
    "email": "ilidio.pedro@gpaangola.co.ao",
    "perfil": "comercial",
    "funcao": "Comercial",
    "metaMensal": 10000000,
    "metaSemanal": 2500000,
    "comissao": 0.03,
    "pesoConversao": 0.4,
    "telefone": "927666777",
    "whatsappNumero": "927666777",
    "foto": "",
    "status": "ativo",
    "silencioso": false,
    "provincia": "Luanda",
    "senha": "gpa2026"
  },
  {
    "id": "u3",
    "nome": "Fernando Leite",
    "email": "fernando.leite@gpaangola.co.ao",
    "perfil": "comercial",
    "funcao": "Comercial",
    "metaMensal": 10000000,
    "metaSemanal": 2500000,
    "comissao": 0.03,
    "pesoConversao": 0.4,
    "telefone": "924333444",
    "whatsappNumero": "924333444",
    "foto": "",
    "status": "ativo",
    "silencioso": false,
    "provincia": "Huambo",
    "senha": "gpa2026"
  },
  {
    "id": "u7",
    "nome": "Carlos Francisco",
    "email": "carlos.francisco@gpaangola.co.ao",
    "perfil": "comercial",
    "funcao": "Comercial",
    "metaMensal": 15000000,
    "metaSemanal": 3750000,
    "comissao": 0.03,
    "pesoConversao": 0.4,
    "telefone": "928111000",
    "whatsappNumero": "928111000",
    "foto": "",
    "status": "ativo",
    "silencioso": false,
    "provincia": "Luanda",
    "senha": "gpa2026"
  },
  {
    "id": "u9",
    "nome": "David Neto",
    "email": "david.neto@gpaangola.co.ao",
    "perfil": "admin",
    "funcao": "Administrador, Gestor & Comercial",
    "metaMensal": 30000000,
    "metaSemanal": 7500000,
    "comissao": 0.03,
    "pesoConversao": 0.4,
    "telefone": "923000000",
    "whatsappNumero": "923000000",
    "foto": "",
    "status": "ativo",
    "silencioso": false,
    "provincia": "Luanda",
    "senha": "gpa2026"
  },
  {
    "id": "u10",
    "nome": "Admin",
    "email": "admin@gpaangola.co.ao",
    "perfil": "admin",
    "funcao": "Administrador Principal",
    "metaMensal": 0,
    "metaSemanal": 0,
    "comissao": 0,
    "pesoConversao": 0,
    "telefone": "922000000",
    "whatsappNumero": "922000000",
    "foto": "",
    "status": "ativo",
    "silencioso": false,
    "provincia": "Luanda",
    "senha": "admin"
  },
  {
    "id": "u11",
    "nome": "Admin1",
    "email": "admin1@gpaangola.co.ao",
    "perfil": "admin",
    "funcao": "Gestor & Administrador",
    "metaMensal": 0,
    "metaSemanal": 0,
    "comissao": 0,
    "pesoConversao": 0,
    "telefone": "922000001",
    "whatsappNumero": "922000001",
    "foto": "",
    "status": "ativo",
    "silencioso": false,
    "provincia": "Luanda",
    "senha": "admin"
  },
  {
    "id": "u12",
    "nome": "Admin2",
    "email": "admin2@gpaangola.co.ao",
    "perfil": "admin",
    "funcao": "Gestor & Administrador",
    "metaMensal": 0,
    "metaSemanal": 0,
    "comissao": 0,
    "pesoConversao": 0,
    "telefone": "922000002",
    "whatsappNumero": "922000002",
    "foto": "",
    "status": "ativo",
    "silencioso": false,
    "provincia": "Luanda",
    "senha": "admin"
  },
  {
    "id": "u16",
    "nome": "Suzete Francisco",
    "email": "suzete.francisco@gpaangola.co.ao",
    "perfil": "comercial",
    "funcao": "Comercial",
    "metaMensal": 25000000,
    "metaSemanal": 6250000,
    "comissao": 0.03,
    "pesoConversao": 0.4,
    "telefone": "928777999",
    "whatsappNumero": "928777999",
    "foto": "",
    "status": "ativo",
    "silencioso": false,
    "provincia": "Luanda",
    "senha": "gpa2026"
  }
];

export const initialClients: Cliente[] = [
  {
    "id": "c_1",
    "nome": "IMOCASAIS",
    "empresa": "IMOCASAIS",
    "nif": "541752000",
    "telefone": "922880248",
    "provincia": "Luanda",
    "segmento": "Média Empresa",
    "status": "ativo",
    "responsavel": "u15",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_2",
    "nome": "SUEZ",
    "empresa": "SUEZ",
    "nif": "541752001",
    "telefone": "922501576",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u15",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_3",
    "nome": "TEIXEIRA DUARTE",
    "empresa": "TEIXEIRA DUARTE",
    "nif": "541752002",
    "telefone": "922794644",
    "provincia": "Luanda",
    "segmento": "Grande Conta / Multinacional",
    "status": "ativo",
    "responsavel": "u15",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 758100
  },
  {
    "id": "c_4",
    "nome": "SIAC",
    "empresa": "SIAC",
    "nif": "541752003",
    "telefone": "922756024",
    "provincia": "Luanda",
    "segmento": "Grande Conta / Multinacional",
    "status": "ativo",
    "responsavel": "u15",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_5",
    "nome": "ALIANÇA SEGUROS",
    "empresa": "ALIANÇA SEGUROS",
    "nif": "541752004",
    "telefone": "922263207",
    "provincia": "Luanda",
    "segmento": "Grande Conta / Multinacional",
    "status": "ativo",
    "responsavel": "u15",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_6",
    "nome": "COSCAL",
    "empresa": "COSCAL",
    "nif": "541752005",
    "telefone": "922994682",
    "provincia": "Luanda",
    "segmento": "Grande Conta / Multinacional",
    "status": "ativo",
    "responsavel": "u15",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 259350
  },
  {
    "id": "c_7",
    "nome": "ENDIAMA",
    "empresa": "ENDIAMA",
    "nif": "541752006",
    "telefone": "922960566",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u15",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_8",
    "nome": "PAY4ALL",
    "empresa": "PAY4ALL",
    "nif": "541752007",
    "telefone": "922490481",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u1",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 2106150
  },
  {
    "id": "c_9",
    "nome": "XPRINT",
    "empresa": "XPRINT",
    "nif": "541752008",
    "telefone": "922681542",
    "provincia": "Luanda",
    "segmento": "Média Empresa",
    "status": "ativo",
    "responsavel": "u1",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_10",
    "nome": "DUBAI INVESTMENTS",
    "empresa": "DUBAI INVESTMENTS",
    "nif": "541752009",
    "telefone": "922990364",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u1",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_11",
    "nome": "BCGA",
    "empresa": "BCGA",
    "nif": "541752010",
    "telefone": "922460250",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u1",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 3135000
  },
  {
    "id": "c_12",
    "nome": "NOSSA SEGUROS",
    "empresa": "NOSSA SEGUROS",
    "nif": "541752011",
    "telefone": "922503547",
    "provincia": "Luanda",
    "segmento": "Grande Conta / Multinacional",
    "status": "ativo",
    "responsavel": "u5",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 5340370
  },
  {
    "id": "c_13",
    "nome": "ATO",
    "empresa": "ATO",
    "nif": "541752012",
    "telefone": "922318483",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u5",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 7695000
  },
  {
    "id": "c_14",
    "nome": "AFRICANA",
    "empresa": "AFRICANA",
    "nif": "541752013",
    "telefone": "922889635",
    "provincia": "Luanda",
    "segmento": "Média Empresa",
    "status": "ativo",
    "responsavel": "u5",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_15",
    "nome": "DISBRA",
    "empresa": "DISBRA",
    "nif": "541752014",
    "telefone": "922806587",
    "provincia": "Luanda",
    "segmento": "Média Empresa",
    "status": "ativo",
    "responsavel": "u5",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 222300
  },
  {
    "id": "c_16",
    "nome": "PRODEL",
    "empresa": "PRODEL",
    "nif": "541752015",
    "telefone": "922432893",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u4",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_17",
    "nome": "JUMUCUZA",
    "empresa": "JUMUCUZA",
    "nif": "541752016",
    "telefone": "922608712",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u4",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_18",
    "nome": "CERTAVE",
    "empresa": "CERTAVE",
    "nif": "541752017",
    "telefone": "922138628",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u4",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_19",
    "nome": "DP-WORLD",
    "empresa": "DP-WORLD",
    "nif": "541752018",
    "telefone": "922780455",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u2",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 3024990
  },
  {
    "id": "c_20",
    "nome": "RHUANITO",
    "empresa": "RHUANITO",
    "nif": "541752019",
    "telefone": "922817666",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u2",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_21",
    "nome": "KERO",
    "empresa": "KERO",
    "nif": "541752020",
    "telefone": "922493311",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u2",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_22",
    "nome": "ACQUA GLOBAL",
    "empresa": "ACQUA GLOBAL",
    "nif": "541752021",
    "telefone": "922180549",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u6",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 2109000
  },
  {
    "id": "c_23",
    "nome": "OMATAPALO",
    "empresa": "OMATAPALO",
    "nif": "541752022",
    "telefone": "922900503",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u6",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_24",
    "nome": "PURIGLASS",
    "empresa": "PURIGLASS",
    "nif": "541752023",
    "telefone": "922682801",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u3",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 706800
  },
  {
    "id": "c_25",
    "nome": "5 LINHAS",
    "empresa": "5 LINHAS",
    "nif": "541752024",
    "telefone": "922523443",
    "provincia": "Luanda",
    "segmento": "Média Empresa",
    "status": "ativo",
    "responsavel": "u3",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_26",
    "nome": "SAAS SISTEMAS TECNOLOGIAS",
    "empresa": "SAAS SISTEMAS TECNOLOGIAS",
    "nif": "541752025",
    "telefone": "922192856",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u3",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 29640
  },
  {
    "id": "c_27",
    "nome": "GRUPO CAJUEIRO",
    "empresa": "GRUPO CAJUEIRO",
    "nif": "541752026",
    "telefone": "922929823",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u3",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 193800
  },
  {
    "id": "c_28",
    "nome": "PEDRA PRECIOSA",
    "empresa": "PEDRA PRECIOSA",
    "nif": "541752027",
    "telefone": "922892445",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u3",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_29",
    "nome": "BAXTTER",
    "empresa": "BAXTTER",
    "nif": "541752028",
    "telefone": "922700048",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u3",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "13/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 444600
  },
  {
    "id": "c_30",
    "nome": "UNITEL",
    "empresa": "UNITEL",
    "nif": "541752029",
    "telefone": "922595727",
    "provincia": "Luanda",
    "segmento": "Grande Conta / Multinacional",
    "status": "ativo",
    "responsavel": "u15",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_31",
    "nome": "FINSTAR/ZAP",
    "empresa": "FINSTAR/ZAP",
    "nif": "541752030",
    "telefone": "922635856",
    "provincia": "Luanda",
    "segmento": "Grande Conta / Multinacional",
    "status": "ativo",
    "responsavel": "u15",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 1687200
  },
  {
    "id": "c_32",
    "nome": "CARPINANGOLA/CASAIS",
    "empresa": "CARPINANGOLA/CASAIS",
    "nif": "541752031",
    "telefone": "922236666",
    "provincia": "Luanda",
    "segmento": "Média Empresa",
    "status": "ativo",
    "responsavel": "u15",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 2017800
  },
  {
    "id": "c_33",
    "nome": "CEGID/PRIMAVERA",
    "empresa": "CEGID/PRIMAVERA",
    "nif": "541752032",
    "telefone": "922282170",
    "provincia": "Luanda",
    "segmento": "Média Empresa",
    "status": "ativo",
    "responsavel": "u15",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 445700
  },
  {
    "id": "c_34",
    "nome": "SBM OFFSHORE",
    "empresa": "SBM OFFSHORE",
    "nif": "541752033",
    "telefone": "922160358",
    "provincia": "Luanda",
    "segmento": "Grande Conta / Multinacional",
    "status": "ativo",
    "responsavel": "u1",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 339150
  },
  {
    "id": "c_35",
    "nome": "TREVOTECH",
    "empresa": "TREVOTECH",
    "nif": "541752034",
    "telefone": "922549126",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u1",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 889200
  },
  {
    "id": "c_36",
    "nome": "ANGOLACA",
    "empresa": "ANGOLACA",
    "nif": "541752035",
    "telefone": "922612513",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u1",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_37",
    "nome": "FADA",
    "empresa": "FADA",
    "nif": "541752036",
    "telefone": "922944356",
    "provincia": "Luanda",
    "segmento": "Média Empresa",
    "status": "ativo",
    "responsavel": "u1",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_38",
    "nome": "PROGRAMA ALIMENTAR",
    "empresa": "PROGRAMA ALIMENTAR",
    "nif": "541752037",
    "telefone": "922985925",
    "provincia": "Luanda",
    "segmento": "Média Empresa",
    "status": "ativo",
    "responsavel": "u5",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_39",
    "nome": "DIVERSIFICA MAIS",
    "empresa": "DIVERSIFICA MAIS",
    "nif": "541752038",
    "telefone": "922339849",
    "provincia": "Luanda",
    "segmento": "Média Empresa",
    "status": "ativo",
    "responsavel": "u5",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_40",
    "nome": "VIAÇÃO E TRÂNSITO",
    "empresa": "VIAÇÃO E TRÂNSITO",
    "nif": "541752039",
    "telefone": "922867814",
    "provincia": "Luanda",
    "segmento": "Grande Conta / Multinacional",
    "status": "ativo",
    "responsavel": "u5",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 7296000
  },
  {
    "id": "c_41",
    "nome": "BANCO BNI",
    "empresa": "BANCO BNI",
    "nif": "541752040",
    "telefone": "922677474",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u4",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_42",
    "nome": "INDÚSTRIAS TOPACK",
    "empresa": "INDÚSTRIAS TOPACK",
    "nif": "541752041",
    "telefone": "922379870",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u4",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_43",
    "nome": "ACADEMIA BAI",
    "empresa": "ACADEMIA BAI",
    "nif": "541752042",
    "telefone": "922984422",
    "provincia": "Luanda",
    "segmento": "Média Empresa",
    "status": "ativo",
    "responsavel": "u2",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_44",
    "nome": "DP WORLD",
    "empresa": "DP WORLD",
    "nif": "541752043",
    "telefone": "922643729",
    "provincia": "Luanda",
    "segmento": "Média Empresa",
    "status": "ativo",
    "responsavel": "u2",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_45",
    "nome": "AUTOMATRIZ",
    "empresa": "AUTOMATRIZ",
    "nif": "541752044",
    "telefone": "922396686",
    "provincia": "Luanda",
    "segmento": "Média Empresa",
    "status": "ativo",
    "responsavel": "u2",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_46",
    "nome": "POLITEJO",
    "empresa": "POLITEJO",
    "nif": "541752045",
    "telefone": "922690136",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u6",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 49590
  },
  {
    "id": "c_47",
    "nome": "RÁDIO NACIONAL DE ANGOLA",
    "empresa": "RÁDIO NACIONAL DE ANGOLA",
    "nif": "541752046",
    "telefone": "922359793",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u6",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_48",
    "nome": "SONANGOL PESQUISA E PRODUÇÃO",
    "empresa": "SONANGOL PESQUISA E PRODUÇÃO",
    "nif": "541752047",
    "telefone": "922436842",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u6",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 7927560
  },
  {
    "id": "c_49",
    "nome": "5 LINHAS TELECOMUNICAÇÕES",
    "empresa": "5 LINHAS TELECOMUNICAÇÕES",
    "nif": "541752048",
    "telefone": "922424409",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u3",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  },
  {
    "id": "c_50",
    "nome": "GRUPO CASTEL",
    "empresa": "GRUPO CASTEL",
    "nif": "541752049",
    "telefone": "922182544",
    "provincia": "Luanda",
    "segmento": "PME",
    "status": "ativo",
    "responsavel": "u3",
    "ultimaVisita": "2026-07-15",
    "proximaVisita": "20/07/2026",
    "endereco": "Luanda, Angola",
    "historicoVendas": 0
  }
];

export const initialVisits: Visita[] = [
  {
    "id": "v1",
    "clienteNome": "UNITEL",
    "empresa": "UNITEL",
    "comercialNome": "Luísa Baltazar",
    "data": "2026-07-13",
    "hora": "09:30",
    "localizacao": "Sede Unitel, Talatona",
    "resultado": "Positivo",
    "produtos": "Canecas e Garrafas Térmicas",
    "necessidade": "Cotação em análise de 96M AOA"
  },
  {
    "id": "v2",
    "clienteNome": "FINSTAR/ZAP",
    "empresa": "FINSTAR/ZAP",
    "comercialNome": "Luísa Baltazar",
    "data": "2026-07-15",
    "hora": "11:00",
    "localizacao": "Sede ZAP, Luanda",
    "resultado": "Positivo",
    "produtos": "Sacos TNT Personalizados",
    "necessidade": "Entrega de 300 unidades concluída"
  },
  {
    "id": "v3",
    "clienteNome": "NOSSA SEGUROS",
    "empresa": "NOSSA SEGUROS",
    "comercialNome": "Marta de Oliveira",
    "data": "2026-07-16",
    "hora": "14:00",
    "localizacao": "Nossa Seguros Luanda",
    "resultado": "Positivo",
    "produtos": "Material para FILDA",
    "necessidade": "Adjudicação aprovada de 2.5M AOA"
  },
  {
    "id": "v4",
    "clienteNome": "SONANGOL PESQUISA E PRODUÇÃO",
    "empresa": "SONANGOL",
    "comercialNome": "Ilídio Pedro",
    "data": "2026-07-14",
    "hora": "10:00",
    "localizacao": "Sonangol Luanda",
    "resultado": "Positivo",
    "produtos": "Brindes para FILDA",
    "necessidade": "Aprovado 7.9M AOA em produção"
  }
];

export const initialDeals: Deal[] = [
  {
    "id": "d_sa_1",
    "semana": "Semana Anterior",
    "clienteNome": "IMOCASAIS",
    "titulo": "Fornecimento de Blocos de nota, canetas Flyers",
    "valor": 1385100,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "negociacao",
    "comercialId": "u15",
    "comercialNome": "Luísa Baltazar",
    "prioridade": "Normal",
    "diasAberto": 14,
    "probabilidade": "40%",
    "proximaAcao": "Entragar em contacto com o cliente para saber o orçamento deles",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta remetida para avaliação",
    "classeCliente": "B",
    "crmStatus": "Aberto",
    "dataEnvio": "09/07/2026"
  },
  {
    "id": "d_sa_2",
    "semana": "Semana Anterior",
    "clienteNome": "SUEZ",
    "titulo": "Fornecimento de Flyers monofolha e tripticos",
    "valor": 6260880,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "negociacao",
    "comercialId": "u15",
    "comercialNome": "Luísa Baltazar",
    "prioridade": "Alta",
    "diasAberto": 16,
    "probabilidade": "80%",
    "proximaAcao": "negociar a modadlidade de pagamento",
    "proximoContacto": "13/07/2026",
    "observacoes": "Falta o envio da PO, para credibilizar a adjudicação do processo",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "07/07/2026"
  },
  {
    "id": "d_sa_3",
    "semana": "Semana Anterior",
    "clienteNome": "TEIXEIRA DUARTE",
    "titulo": "Fornecimento de Diversos",
    "valor": 758100,
    "valorAprovado": 758100,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u15",
    "comercialNome": "Luísa Baltazar",
    "prioridade": "Alta",
    "diasAberto": 17,
    "probabilidade": "100%",
    "proximaAcao": "Aumentar o fluxo de trabalhos com este cliente",
    "proximoContacto": "13/07/2026",
    "observacoes": "As artes já foram aprovadas",
    "classeCliente": "A",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "06/07/2026"
  },
  {
    "id": "d_sa_4",
    "semana": "Semana Anterior",
    "clienteNome": "SIAC",
    "titulo": "Fornecimento de brindes e merchandising",
    "valor": 19418760,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u15",
    "comercialNome": "Luísa Baltazar",
    "prioridade": "Média",
    "diasAberto": 16,
    "probabilidade": "40%",
    "proximaAcao": "Agendar uma reunião com o cliente",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta remetida para validação",
    "classeCliente": "A",
    "crmStatus": "Aberto",
    "dataEnvio": "07/07/2026"
  },
  {
    "id": "d_sa_5",
    "semana": "Semana Anterior",
    "clienteNome": "ALIANÇA SEGUROS",
    "titulo": "Fornecimento de Flyers dipticos",
    "valor": 3328800,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u15",
    "comercialNome": "Luísa Baltazar",
    "prioridade": "Normal",
    "diasAberto": 15,
    "probabilidade": "40%",
    "proximaAcao": "Considerar a possibilidade de apresentar um desconto",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta remetida para validação",
    "classeCliente": "A",
    "crmStatus": "Aberto",
    "dataEnvio": "08/07/2026"
  },
  {
    "id": "d_sa_6",
    "semana": "Semana Anterior",
    "clienteNome": "COSCAL",
    "titulo": "Fornecimento de flyers Tripticos",
    "valor": 259350,
    "valorAprovado": 259350,
    "valorPerdido": 0,
    "etapa": "producao",
    "comercialId": "u15",
    "comercialNome": "Luísa Baltazar",
    "prioridade": "Alta",
    "diasAberto": 14,
    "probabilidade": "100%",
    "proximaAcao": "Conseguir o contacto do cliente final",
    "proximoContacto": "13/07/2026",
    "observacoes": "Material produzido e entregue",
    "classeCliente": "A",
    "crmStatus": "Aberto",
    "dataEnvio": "09/07/2026"
  },
  {
    "id": "d_sa_7",
    "semana": "Semana Anterior",
    "clienteNome": "ENDIAMA",
    "titulo": "Fornecimento de materiais para outubro rosa",
    "valor": 6958560,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "negociacao",
    "comercialId": "u15",
    "comercialNome": "Luísa Baltazar",
    "prioridade": "Alta",
    "diasAberto": 37,
    "probabilidade": "80%",
    "proximaAcao": "negociar a modadlidade de pagamento",
    "proximoContacto": "13/07/2026",
    "observacoes": "Falta o envio da PO, para credibilizar a adjudicação do processo",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "16/06/2026"
  },
  {
    "id": "d_sa_8",
    "semana": "Semana Anterior",
    "clienteNome": "PAY4ALL",
    "titulo": "Fornecimento de Brindes para a filda",
    "valor": 2106150,
    "valorAprovado": 2106150,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u1",
    "comercialNome": "Amélia Cassinda",
    "prioridade": "Alta",
    "diasAberto": 28,
    "probabilidade": "100%",
    "proximaAcao": "Acompanharo processo de produção externa e interna, para cumprir com o prazo",
    "proximoContacto": "13/07/2026",
    "observacoes": "Avaliação e criação de artes finais para produção",
    "classeCliente": "C",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "25/06/2026"
  },
  {
    "id": "d_sa_9",
    "semana": "Semana Anterior",
    "clienteNome": "XPRINT",
    "titulo": "Fornecimento de Brindes e Têxtil",
    "valor": 2350680,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u1",
    "comercialNome": "Amélia Cassinda",
    "prioridade": "Normal",
    "diasAberto": 17,
    "probabilidade": "40%",
    "proximaAcao": "Considerar a possibilidade de apresentar um desconto",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta remetida para avaliação",
    "classeCliente": "B",
    "crmStatus": "Aberto",
    "dataEnvio": "06/07/2026"
  },
  {
    "id": "d_sa_10",
    "semana": "Semana Anterior",
    "clienteNome": "DUBAI INVESTMENTS",
    "titulo": "Forneciemnto de Brindes",
    "valor": 6156000,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u1",
    "comercialNome": "Amélia Cassinda",
    "prioridade": "Média",
    "diasAberto": 13,
    "probabilidade": "50%",
    "proximaAcao": "Apresentar amostras Físicas e acompanhar o processo",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta remetida para avaliação",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "10/07/2026"
  },
  {
    "id": "d_sa_11",
    "semana": "Semana Anterior",
    "clienteNome": "DUBAI INVESTMENTS",
    "titulo": "Fornecimento de Flyrs",
    "valor": 3249000,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u1",
    "comercialNome": "Amélia Cassinda",
    "prioridade": "Normal",
    "diasAberto": 15,
    "probabilidade": "40%",
    "proximaAcao": "Apresentar amostras Físicas e acompanhar o processo",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta remetida para avaliação",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "08/07/2026"
  },
  {
    "id": "d_sa_12",
    "semana": "Semana Anterior",
    "clienteNome": "BCGA",
    "titulo": "Fornecimento de Lenços e gravatas",
    "valor": 9095000,
    "valorAprovado": 0,
    "valorPerdido": 9095000,
    "etapa": "perdido",
    "comercialId": "u1",
    "comercialNome": "Amélia Cassinda",
    "prioridade": "Média",
    "diasAberto": 17,
    "probabilidade": "0%",
    "proximaAcao": "Apresentação de disponibilidade para futurod projectos",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta rejeitada, por causa do tempo de produção e pelo fornecedor não ter o mesmo tecido",
    "classeCliente": "C",
    "crmStatus": "Fechado perdido",
    "dataEnvio": "06/07/2026"
  },
  {
    "id": "d_sa_13",
    "semana": "Semana Anterior",
    "clienteNome": "BCGA",
    "titulo": "Fornecimento de Fita Tulyy",
    "valor": 2684700,
    "valorAprovado": 0,
    "valorPerdido": 2684700,
    "etapa": "perdido",
    "comercialId": "u1",
    "comercialNome": "Amélia Cassinda",
    "prioridade": "Normal",
    "diasAberto": 20,
    "probabilidade": "0%",
    "proximaAcao": "Apresentação de disponibilidade para futurod projectos",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta reajustada por falta de amostras físicas",
    "classeCliente": "A",
    "crmStatus": "Fechado perdido",
    "dataEnvio": "03/07/2026"
  },
  {
    "id": "d_sa_14",
    "semana": "Semana Anterior",
    "clienteNome": "NOSSA SEGUROS",
    "titulo": "Fornecimento de Material para filda",
    "valor": 2809820,
    "valorAprovado": 2809820,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u5",
    "comercialNome": "Marta de Oliveira",
    "prioridade": "Alta",
    "diasAberto": 16,
    "probabilidade": "100%",
    "proximaAcao": "Dar inicio ao processo de produção",
    "proximoContacto": "13/07/2026",
    "observacoes": "Acompanhar o processo até ao fecho para assegurar a entrega na data prevista",
    "classeCliente": "A",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "07/07/2026"
  },
  {
    "id": "d_sa_15",
    "semana": "Semana Anterior",
    "clienteNome": "ATO",
    "titulo": "Fornecimento de brindes para Filda",
    "valor": 7695000,
    "valorAprovado": 7695000,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u5",
    "comercialNome": "Marta de Oliveira",
    "prioridade": "Alta",
    "diasAberto": 17,
    "probabilidade": "100%",
    "proximaAcao": "Dar inicio ao processo de produção",
    "proximoContacto": "13/07/2026",
    "observacoes": "Acompanhar o processo até ao fecho para assegurar a entrega na data prevista",
    "classeCliente": "C",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "06/07/2026"
  },
  {
    "id": "d_sa_16",
    "semana": "Semana Anterior",
    "clienteNome": "AFRICANA",
    "titulo": "Fornecimento de material de letras monobloco",
    "valor": 12398174.88,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "negociacao",
    "comercialId": "u5",
    "comercialNome": "Marta de Oliveira",
    "prioridade": "Média",
    "diasAberto": 14,
    "probabilidade": "50%",
    "proximaAcao": "Acompanhamento do Processo até o fecho",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta remetida para avaliação",
    "classeCliente": "B",
    "crmStatus": "Aberto",
    "dataEnvio": "09/07/2026"
  },
  {
    "id": "d_sa_17",
    "semana": "Semana Anterior",
    "clienteNome": "DISBRA",
    "titulo": "Fornecimento de sacolas e folhetos",
    "valor": 222300,
    "valorAprovado": 222300,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u5",
    "comercialNome": "Marta de Oliveira",
    "prioridade": "Alta",
    "diasAberto": 16,
    "probabilidade": "100%",
    "proximaAcao": "Pressionar o envio das artes",
    "proximoContacto": "13/07/2026",
    "observacoes": "No aguardo das artes para produção",
    "classeCliente": "B",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "07/07/2026"
  },
  {
    "id": "d_sa_18",
    "semana": "Semana Anterior",
    "clienteNome": "PRODEL",
    "titulo": "Fornecimento de Tapetes",
    "valor": 28581282,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u4",
    "comercialNome": "José Neto",
    "prioridade": "Média",
    "diasAberto": 16,
    "probabilidade": "50%",
    "proximaAcao": "Negociar com o cliente, considerar a possibilidade de desconto, marcar uma reunião",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta remetida para avaliação",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "07/07/2026"
  },
  {
    "id": "d_sa_19",
    "semana": "Semana Anterior",
    "clienteNome": "JUMUCUZA",
    "titulo": "Fornecimento de protedores auditivos",
    "valor": 953610,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u4",
    "comercialNome": "José Neto",
    "prioridade": "Normal",
    "diasAberto": 15,
    "probabilidade": "40%",
    "proximaAcao": "Solicitar o ponto de situação da proposta",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta remetida para avaliação, juntos com as ficha técnica",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "08/07/2026"
  },
  {
    "id": "d_sa_20",
    "semana": "Semana Anterior",
    "clienteNome": "CERTAVE",
    "titulo": "Fornecimento de sinaletica",
    "valor": 1997394,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u4",
    "comercialNome": "José Neto",
    "prioridade": "Normal",
    "diasAberto": 13,
    "probabilidade": "40%",
    "proximaAcao": "Monitorizar o proc. De adjudicação e manter disponibilidade para envetuais ajustes",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta remetida para avaliação, juntos com as ficha técnica",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "10/07/2026"
  },
  {
    "id": "d_sa_21",
    "semana": "Semana Anterior",
    "clienteNome": "DP-WORLD",
    "titulo": "Fornecimeto de Brindes",
    "valor": 3024990,
    "valorAprovado": 3024990,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u2",
    "comercialNome": "David Guedes",
    "prioridade": "Alta",
    "diasAberto": 15,
    "probabilidade": "100%",
    "proximaAcao": "Aguardar pelo envio das artes",
    "proximoContacto": "13/07/2026",
    "observacoes": "Entrega prevista para o dia 13 do mês corrente",
    "classeCliente": "C",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "08/07/2026"
  },
  {
    "id": "d_sa_22",
    "semana": "Semana Anterior",
    "clienteNome": "RHUANITO",
    "titulo": "Fornecimento de Flyres e têxtil",
    "valor": 687420,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "negociacao",
    "comercialId": "u2",
    "comercialNome": "David Guedes",
    "prioridade": "Alta",
    "diasAberto": 13,
    "probabilidade": "80%",
    "proximaAcao": "Solicitar o ponto de situação da proposta",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta remetida para avaliação",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "10/07/2026"
  },
  {
    "id": "d_sa_23",
    "semana": "Semana Anterior",
    "clienteNome": "KERO",
    "titulo": "Fornecimeto de Brindes",
    "valor": 221160,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u2",
    "comercialNome": "David Guedes",
    "prioridade": "Normal",
    "diasAberto": 13,
    "probabilidade": "40%",
    "proximaAcao": "Solicitar o ponto de situação da proposta",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta remetida para avaliação",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "10/07/2026"
  },
  {
    "id": "d_sa_24",
    "semana": "Semana Anterior",
    "clienteNome": "ACQUA GLOBAL",
    "titulo": "Fornecimento de pins",
    "valor": 2109000,
    "valorAprovado": 2109000,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u6",
    "comercialNome": "Ilídio Pedro",
    "prioridade": "Alta",
    "diasAberto": 16,
    "probabilidade": "100%",
    "proximaAcao": "Dar inicio ao processo de produção",
    "proximoContacto": "13/07/2026",
    "observacoes": "Acompanhar o processo até ao fecho para assegurar a entrega na data prevista",
    "classeCliente": "C",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "07/07/2026"
  },
  {
    "id": "d_sa_25",
    "semana": "Semana Anterior",
    "clienteNome": "OMATAPALO",
    "titulo": "Fornecimento De Placas sinaleticas",
    "valor": 21909090,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u6",
    "comercialNome": "Ilídio Pedro",
    "prioridade": "Média",
    "diasAberto": 17,
    "probabilidade": "20%",
    "proximaAcao": "Solicitar o ponto de situação da proposta",
    "proximoContacto": "13/07/2026",
    "observacoes": "O cliente não respondeu ao nosso e-mail, mas tem pouca chances de ser aprovada a nossa proposta",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "06/07/2026"
  },
  {
    "id": "d_sa_26",
    "semana": "Semana Anterior",
    "clienteNome": "PURIGLASS",
    "titulo": "Fornecimento de T-sirts, autocolantes cartão de visita",
    "valor": 706800,
    "valorAprovado": 706800,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u3",
    "comercialNome": "Fernando Leite",
    "prioridade": "Alta",
    "diasAberto": 15,
    "probabilidade": "100%",
    "proximaAcao": "Entregar o material ao cliente",
    "proximoContacto": "13/07/2026",
    "observacoes": "Acompanhar o processo até ao fecho para assegurar a entrega na data prevista",
    "classeCliente": "C",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "08/07/2026"
  },
  {
    "id": "d_sa_27",
    "semana": "Semana Anterior",
    "clienteNome": "5 LINHAS",
    "titulo": "Fornecimento de diversos",
    "valor": 8468775,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u3",
    "comercialNome": "Fernando Leite",
    "prioridade": "Média",
    "diasAberto": 13,
    "probabilidade": "40%",
    "proximaAcao": "Solicitar o ponto de situação da proposta",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta remetida para avaliação",
    "classeCliente": "B",
    "crmStatus": "Aberto",
    "dataEnvio": "10/07/2026"
  },
  {
    "id": "d_sa_28",
    "semana": "Semana Anterior",
    "clienteNome": "SAAS SISTEMAS TECNOLOGIAS",
    "titulo": "Fornecimento de passes",
    "valor": 29640,
    "valorAprovado": 29640,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u3",
    "comercialNome": "Fernando Leite",
    "prioridade": "Alta",
    "diasAberto": 13,
    "probabilidade": "100%",
    "proximaAcao": "Entregar o material ao cliente",
    "proximoContacto": "13/07/2026",
    "observacoes": "Acompanhar o processo até ao fecho para assegurar a entrega na data prevista",
    "classeCliente": "C",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "10/07/2026"
  },
  {
    "id": "d_sa_29",
    "semana": "Semana Anterior",
    "clienteNome": "GRUPO CAJUEIRO",
    "titulo": "Fornecimento de cartões de visitas",
    "valor": 193800,
    "valorAprovado": 193800,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u3",
    "comercialNome": "Fernando Leite",
    "prioridade": "Alta",
    "diasAberto": 18,
    "probabilidade": "100%",
    "proximaAcao": "Entregar o material ao cliente",
    "proximoContacto": "13/07/2026",
    "observacoes": "Acompanhar o processo até ao fecho para assegurar a entrega na data prevista",
    "classeCliente": "C",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "05/07/2026"
  },
  {
    "id": "d_sa_30",
    "semana": "Semana Anterior",
    "clienteNome": "PEDRA PRECIOSA",
    "titulo": "Fornecimento de toalhas bordadas",
    "valor": 251370,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "negociacao",
    "comercialId": "u3",
    "comercialNome": "Fernando Leite",
    "prioridade": "Média",
    "diasAberto": 16,
    "probabilidade": "60%",
    "proximaAcao": "Solicitar o ponto de situação da proposta",
    "proximoContacto": "13/07/2026",
    "observacoes": "A guardando a confirmação do cliente sobra a aprovação",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "07/07/2026"
  },
  {
    "id": "d_sa_31",
    "semana": "Semana Anterior",
    "clienteNome": "BAXTTER",
    "titulo": "Fornecimento de brindes e flyres",
    "valor": 1657560,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u3",
    "comercialNome": "Fernando Leite",
    "prioridade": "Normal",
    "diasAberto": 13,
    "probabilidade": "40%",
    "proximaAcao": "Solicitar o ponto de situação da proposta",
    "proximoContacto": "13/07/2026",
    "observacoes": "Proposta remetida para avaliação",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "10/07/2026"
  },
  {
    "id": "d_sf_32",
    "semana": "Semana Finda",
    "clienteNome": "UNITEL",
    "titulo": "Canecas de Porcelana e Garrafas Térmica",
    "valor": 96124800,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u15",
    "comercialNome": "Luísa Baltazar",
    "prioridade": "Alta",
    "diasAberto": 10,
    "probabilidade": "40%",
    "proximaAcao": "Incentivar o cliente para o envio da contraproposta.",
    "proximoContacto": "20/07/2026",
    "observacoes": "O processo de análise das propostas está em curso",
    "classeCliente": "A",
    "crmStatus": "Aberto",
    "dataEnvio": "13/07/2026"
  },
  {
    "id": "d_sf_33",
    "semana": "Semana Finda",
    "clienteNome": "FINSTAR/ZAP",
    "titulo": "Sacos TNT Personalizados",
    "valor": 1687200,
    "valorAprovado": 1687200,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u15",
    "comercialNome": "Luísa Baltazar",
    "prioridade": "Média",
    "diasAberto": 8,
    "probabilidade": "100%",
    "proximaAcao": "Pressionar a adjudicação da proposta das T-Shirts",
    "proximoContacto": "20/07/2026",
    "observacoes": "Já entregamos 300 unidades. A entrega será concluída no dia 20 de Julho",
    "classeCliente": "A",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "15/07/2026"
  },
  {
    "id": "d_sf_34",
    "semana": "Semana Finda",
    "clienteNome": "FINSTAR/ZAP",
    "titulo": "T-Shirts para Lojistas",
    "valor": 21161250,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "negociacao",
    "comercialId": "u15",
    "comercialNome": "Luísa Baltazar",
    "prioridade": "Alta",
    "diasAberto": 9,
    "probabilidade": "60%",
    "proximaAcao": "Solicitar o ponto de situação da PO",
    "proximoContacto": "20/07/2026",
    "observacoes": "Aguardamos a formalização da adjudicação",
    "classeCliente": "A",
    "crmStatus": "Aberto",
    "dataEnvio": "14/07/2026"
  },
  {
    "id": "d_sf_35",
    "semana": "Semana Finda",
    "clienteNome": "CARPINANGOLA/CASAIS",
    "titulo": "Bloco de Notas e Canetas",
    "valor": 2017800,
    "valorAprovado": 2017800,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u15",
    "comercialNome": "Luísa Baltazar",
    "prioridade": "Alta",
    "diasAberto": 8,
    "probabilidade": "100%",
    "proximaAcao": "Alinhamento com a cliente para obter mais trabalhos",
    "proximoContacto": "20/07/2026",
    "observacoes": "O processo de produção está em curso, faremos a entrega no dia 20 de Julho",
    "classeCliente": "B",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "15/07/2026"
  },
  {
    "id": "d_sf_36",
    "semana": "Semana Finda",
    "clienteNome": "CEGID/PRIMAVERA",
    "titulo": "Impressão de Flyers",
    "valor": 445700,
    "valorAprovado": 445700,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u15",
    "comercialNome": "Luísa Baltazar",
    "prioridade": "Alta",
    "diasAberto": 6,
    "probabilidade": "100%",
    "proximaAcao": "Cumprimento do prazo de entrega",
    "proximoContacto": "20/07/2026",
    "observacoes": "O processo de produção está em curso, faremos a entrega no dia 20 de Julho",
    "classeCliente": "B",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "17/07/2026"
  },
  {
    "id": "d_sf_37",
    "semana": "Semana Finda",
    "clienteNome": "FINSTAR/ZAP",
    "titulo": "T-Shirts para Filda",
    "valor": 1966500,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u15",
    "comercialNome": "Luísa Baltazar",
    "prioridade": "Normal",
    "diasAberto": 6,
    "probabilidade": "50%",
    "proximaAcao": "Persuadir a aprovação usando o prazo de entrega do estratégia",
    "proximoContacto": "20/07/2026",
    "observacoes": "As propostas ainda estão a ser analisadas",
    "classeCliente": "A",
    "crmStatus": "Aberto",
    "dataEnvio": "17/07/2026"
  },
  {
    "id": "d_sf_38",
    "semana": "Semana Finda",
    "clienteNome": "SIAC",
    "titulo": "Totens em Betão",
    "valor": 29641900,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u15",
    "comercialNome": "Luísa Baltazar",
    "prioridade": "Normal",
    "diasAberto": 7,
    "probabilidade": "40%",
    "proximaAcao": "Solicitar uma reunião com este cliente",
    "proximoContacto": "20/07/2026",
    "observacoes": "A nossa proposta foi submetida para avaliação",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "16/07/2026"
  },
  {
    "id": "d_sf_39",
    "semana": "Semana Finda",
    "clienteNome": "SBM OFFSHORE",
    "titulo": "Impressão de Autocolante",
    "valor": 339150,
    "valorAprovado": 339150,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u1",
    "comercialNome": "Amélia Cassinda",
    "prioridade": "Normal",
    "diasAberto": 44,
    "probabilidade": "100%",
    "proximaAcao": "Entrega do material ao cliente",
    "proximoContacto": "20/07/2026",
    "observacoes": "O material está pronto para ser entregue",
    "classeCliente": "A",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "09/06/2026"
  },
  {
    "id": "d_sf_40",
    "semana": "Semana Finda",
    "clienteNome": "BCGA",
    "titulo": "Fornecimento de Sacolas",
    "valor": 3135000,
    "valorAprovado": 3135000,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u1",
    "comercialNome": "Amélia Cassinda",
    "prioridade": "Alta",
    "diasAberto": 10,
    "probabilidade": "100%",
    "proximaAcao": "Levantar o material do cliente no fornecedor",
    "proximoContacto": "20/07/2026",
    "observacoes": "Material em produção no fornecedor",
    "classeCliente": "A",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "13/07/2026"
  },
  {
    "id": "d_sf_41",
    "semana": "Semana Finda",
    "clienteNome": "TREVOTECH",
    "titulo": "Fornecimento de Polos",
    "valor": 889200,
    "valorAprovado": 889200,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u1",
    "comercialNome": "Amélia Cassinda",
    "prioridade": "Normal",
    "diasAberto": 10,
    "probabilidade": "100%",
    "proximaAcao": "Solicitar feedback do material entregue",
    "proximoContacto": "20/07/2026",
    "observacoes": "Material produzido e entregue",
    "classeCliente": "C",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "13/07/2026"
  },
  {
    "id": "d_sf_42",
    "semana": "Semana Finda",
    "clienteNome": "ANGOLACA",
    "titulo": "Fornecimento de Materiais Diversos",
    "valor": 14248432.5,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u1",
    "comercialNome": "Amélia Cassinda",
    "prioridade": "Média",
    "diasAberto": 6,
    "probabilidade": "50%",
    "proximaAcao": "Contactar a cliente para agendar uma reunião",
    "proximoContacto": "20/07/2026",
    "observacoes": "Proposta remetida para avaliação",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "17/07/2026"
  },
  {
    "id": "d_sf_43",
    "semana": "Semana Finda",
    "clienteNome": "DUBAI INVESTMENTS",
    "titulo": "Fornecimento de Garrafas Térmicas",
    "valor": 29724360,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u1",
    "comercialNome": "Amélia Cassinda",
    "prioridade": "Média",
    "diasAberto": 9,
    "probabilidade": "40%",
    "proximaAcao": "Avaliar a possibilidade de dar um desconto",
    "proximoContacto": "20/07/2026",
    "observacoes": "Proposta remetida para avaliação",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "14/07/2026"
  },
  {
    "id": "d_sf_44",
    "semana": "Semana Finda",
    "clienteNome": "FADA",
    "titulo": "Fornecimento de Brindes",
    "valor": 3583000,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u1",
    "comercialNome": "Amélia Cassinda",
    "prioridade": "Média",
    "diasAberto": 6,
    "probabilidade": "40%",
    "proximaAcao": "Solicitar o ponto de situação da proposta",
    "proximoContacto": "20/07/2026",
    "observacoes": "Proposta remetida para avaliação",
    "classeCliente": "B",
    "crmStatus": "Aberto",
    "dataEnvio": "17/07/2026"
  },
  {
    "id": "d_sf_45",
    "semana": "Semana Finda",
    "clienteNome": "NOSSA SEGUROS",
    "titulo": "Fornecimento de Material para Filda",
    "valor": 2530550,
    "valorAprovado": 2530550,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u5",
    "comercialNome": "Marta de Oliveira",
    "prioridade": "Alta",
    "diasAberto": 7,
    "probabilidade": "100%",
    "proximaAcao": "Dar inicio ao processo de produção",
    "proximoContacto": "20/07/2026",
    "observacoes": "Acompanhamento até finalizar o processo de produção",
    "classeCliente": "B",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "16/07/2026"
  },
  {
    "id": "d_sf_46",
    "semana": "Semana Finda",
    "clienteNome": "PROGRAMA ALIMENTAR",
    "titulo": "Fornecimento de Materiais Diversos",
    "valor": 7060875,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "negociacao",
    "comercialId": "u5",
    "comercialNome": "Marta de Oliveira",
    "prioridade": "Normal",
    "diasAberto": 6,
    "probabilidade": "40%",
    "proximaAcao": "Solicitar um feedback do orçamento",
    "proximoContacto": "20/07/2026",
    "observacoes": "A nossa proposta está em análise",
    "classeCliente": "B",
    "crmStatus": "Aberto",
    "dataEnvio": "17/07/2026"
  },
  {
    "id": "d_sf_47",
    "semana": "Semana Finda",
    "clienteNome": "DIVERSIFICA MAIS",
    "titulo": "Fornecimento de Passes PVC e Fitas",
    "valor": 422712,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u5",
    "comercialNome": "Marta de Oliveira",
    "prioridade": "Normal",
    "diasAberto": 9,
    "probabilidade": "40%",
    "proximaAcao": "Solicitar um feedback do orçamento",
    "proximoContacto": "20/07/2026",
    "observacoes": "Apresentamos a proposta e aguardamos feedback do cliente",
    "classeCliente": "B",
    "crmStatus": "Aberto",
    "dataEnvio": "14/07/2026"
  },
  {
    "id": "d_sf_48",
    "semana": "Semana Finda",
    "clienteNome": "ATO",
    "titulo": "Fornecimento e Montagem de Sinaléticas",
    "valor": 1983600,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u5",
    "comercialNome": "Marta de Oliveira",
    "prioridade": "Normal",
    "diasAberto": 7,
    "probabilidade": "40%",
    "proximaAcao": "Contactar o cliente para impulsionar a adjudicação",
    "proximoContacto": "20/07/2026",
    "observacoes": "A nossa proposta está em análise",
    "classeCliente": "B",
    "crmStatus": "Aberto",
    "dataEnvio": "16/07/2026"
  },
  {
    "id": "d_sf_49",
    "semana": "Semana Finda",
    "clienteNome": "VIAÇÃO E TRÂNSITO",
    "titulo": "Flyers e Roll Ups",
    "valor": 7296000,
    "valorAprovado": 7296000,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u5",
    "comercialNome": "Marta de Oliveira",
    "prioridade": "Alta",
    "diasAberto": 6,
    "probabilidade": "100%",
    "proximaAcao": "Solicitar o envio das artes para a produção",
    "proximoContacto": "20/07/2026",
    "observacoes": "As artes serão partiilhadas na segunda-feira",
    "classeCliente": "A",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "17/07/2026"
  },
  {
    "id": "d_sf_50",
    "semana": "Semana Finda",
    "clienteNome": "BANCO BNI",
    "titulo": "Impressão de Flyers",
    "valor": 881448,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u4",
    "comercialNome": "José Neto",
    "prioridade": "Normal",
    "diasAberto": 10,
    "probabilidade": "40%",
    "proximaAcao": "Solicitar a contraproposta do cliente",
    "proximoContacto": "20/07/2026",
    "observacoes": "Não tivemos feedback da nossa proposta",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "13/07/2026"
  },
  {
    "id": "d_sf_51",
    "semana": "Semana Finda",
    "clienteNome": "PRODEL",
    "titulo": "Plotagem de Viatura",
    "valor": 1539000,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u4",
    "comercialNome": "José Neto",
    "prioridade": "Média",
    "diasAberto": 9,
    "probabilidade": "40%",
    "proximaAcao": "Considerar a possibilidade de apresentar um desconto",
    "proximoContacto": "20/07/2026",
    "observacoes": "A nossa proposta está a ser analisada pelo cliente",
    "classeCliente": "B",
    "crmStatus": "Aberto",
    "dataEnvio": "14/07/2026"
  },
  {
    "id": "d_sf_52",
    "semana": "Semana Finda",
    "clienteNome": "INDÚSTRIAS TOPACK",
    "titulo": "Coletes Multibolso e Cartões de Visita",
    "valor": 2374050,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u4",
    "comercialNome": "José Neto",
    "prioridade": "Normal",
    "diasAberto": 9,
    "probabilidade": "40%",
    "proximaAcao": "Contactar o cliente para negociar a proposta",
    "proximoContacto": "20/07/2026",
    "observacoes": "Apresentamos a proposta e aguardamos feedback do cliente",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "14/07/2026"
  },
  {
    "id": "d_sf_53",
    "semana": "Semana Finda",
    "clienteNome": "ACADEMIA BAI",
    "titulo": "Brindes e Materiais de Merchandising",
    "valor": 3169713,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u2",
    "comercialNome": "David Guedes",
    "prioridade": "Normal",
    "diasAberto": 7,
    "probabilidade": "40%",
    "proximaAcao": "Contactar o cliente para saber se recebeu a proposta",
    "proximoContacto": "20/07/2026",
    "observacoes": "Enviamos a proposta mas o cliente não deu feedback",
    "classeCliente": "B",
    "crmStatus": "Aberto",
    "dataEnvio": "16/07/2026"
  },
  {
    "id": "d_sf_54",
    "semana": "Semana Finda",
    "clienteNome": "DP WORLD",
    "titulo": "Placas em PVC com Vinil",
    "valor": 1962624,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "negociacao",
    "comercialId": "u2",
    "comercialNome": "David Guedes",
    "prioridade": "Alta",
    "diasAberto": 6,
    "probabilidade": "50%",
    "proximaAcao": "Persuadir a aprovação",
    "proximoContacto": "20/07/2026",
    "observacoes": "Já oferecemos um desconto na proposta",
    "classeCliente": "B",
    "crmStatus": "Aberto",
    "dataEnvio": "17/07/2026"
  },
  {
    "id": "d_sf_55",
    "semana": "Semana Finda",
    "clienteNome": "DP WORLD",
    "titulo": "Quadros em Acrílico para Documentos",
    "valor": 1590300,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u2",
    "comercialNome": "David Guedes",
    "prioridade": "Alta",
    "diasAberto": 7,
    "probabilidade": "50%",
    "proximaAcao": "Considerar a possibilidade de apresentar um desconto",
    "proximoContacto": "20/07/2026",
    "observacoes": "A nossa proposta está a ser analisada pelo cliente",
    "classeCliente": "B",
    "crmStatus": "Aberto",
    "dataEnvio": "16/07/2026"
  },
  {
    "id": "d_sf_56",
    "semana": "Semana Finda",
    "clienteNome": "DP WORLD",
    "titulo": "Fornecimento de Materiais Diversos",
    "valor": 1133502,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u2",
    "comercialNome": "David Guedes",
    "prioridade": "Alta",
    "diasAberto": 8,
    "probabilidade": "50%",
    "proximaAcao": "Entrar em contacto com o cliente e persuadir o fecho",
    "proximoContacto": "20/07/2026",
    "observacoes": "Enviamos a proposta e aguardamos feedback do cliente",
    "classeCliente": "B",
    "crmStatus": "Aberto",
    "dataEnvio": "15/07/2026"
  },
  {
    "id": "d_sf_57",
    "semana": "Semana Finda",
    "clienteNome": "AUTOMATRIZ",
    "titulo": "Fornecimento e Aplicação de Lona",
    "valor": 405840,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "negociacao",
    "comercialId": "u2",
    "comercialNome": "David Guedes",
    "prioridade": "Normal",
    "diasAberto": 9,
    "probabilidade": "50%",
    "proximaAcao": "Produção da amostra solicitada",
    "proximoContacto": "20/07/2026",
    "observacoes": "A princípio rejeitamos a produção da amostra, mas vamos analisar melhor",
    "classeCliente": "B",
    "crmStatus": "Aberto",
    "dataEnvio": "14/07/2026"
  },
  {
    "id": "d_sf_58",
    "semana": "Semana Finda",
    "clienteNome": "POLITEJO",
    "titulo": "Impressão de Vinil Autocolante",
    "valor": 49590,
    "valorAprovado": 49590,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u6",
    "comercialNome": "Ilídio Pedro",
    "prioridade": "Média",
    "diasAberto": 6,
    "probabilidade": "100%",
    "proximaAcao": "Manter o contacto com o cliente para gerar novos negócios",
    "proximoContacto": "20/07/2026",
    "observacoes": "O material já foi produzido",
    "classeCliente": "C",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "17/07/2026"
  },
  {
    "id": "d_sf_59",
    "semana": "Semana Finda",
    "clienteNome": "RÁDIO NACIONAL DE ANGOLA",
    "titulo": "Brindes para Filda",
    "valor": 3243300,
    "valorAprovado": 0,
    "valorPerdido": 3243300,
    "etapa": "perdido",
    "comercialId": "u6",
    "comercialNome": "Ilídio Pedro",
    "prioridade": "Baixa",
    "diasAberto": 9,
    "probabilidade": "0%",
    "proximaAcao": "Negociar a parceria com este cliente",
    "proximoContacto": "20/07/2026",
    "observacoes": "A parceria proposta pelo cliente era apenas benéfica para eles",
    "classeCliente": "C",
    "crmStatus": "Fechado perdido",
    "dataEnvio": "14/07/2026"
  },
  {
    "id": "d_sf_60",
    "semana": "Semana Finda",
    "clienteNome": "SONANGOL PESQUISA E PRODUÇÃO",
    "titulo": "Brindes para Filda",
    "valor": 7927560,
    "valorAprovado": 7927560,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u6",
    "comercialNome": "Ilídio Pedro",
    "prioridade": "Alta",
    "diasAberto": 9,
    "probabilidade": "100%",
    "proximaAcao": "Cumprimento do prazo de entrega",
    "proximoContacto": "20/07/2026",
    "observacoes": "O material está em produção",
    "classeCliente": "C",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "14/07/2026"
  },
  {
    "id": "d_sf_61",
    "semana": "Semana Finda",
    "clienteNome": "5 LINHAS TELECOMUNICAÇÕES",
    "titulo": "Brindes, Têxteis e Papelaria",
    "valor": 8468775,
    "valorAprovado": 0,
    "valorPerdido": 8468775,
    "etapa": "perdido",
    "comercialId": "u3",
    "comercialNome": "Fernando Leite",
    "prioridade": "Normal",
    "diasAberto": 15,
    "probabilidade": "0%",
    "proximaAcao": "Apresentar outras soluções ao cliente",
    "proximoContacto": "20/07/2026",
    "observacoes": "O cliente optou por avançar com outro fornecedor",
    "classeCliente": "C",
    "crmStatus": "Fechado perdido",
    "dataEnvio": "08/07/2026"
  },
  {
    "id": "d_sf_62",
    "semana": "Semana Finda",
    "clienteNome": "GRUPO CASTEL",
    "titulo": "Impressão de Código de Conduta",
    "valor": 6002100,
    "valorAprovado": 0,
    "valorPerdido": 0,
    "etapa": "proposta",
    "comercialId": "u3",
    "comercialNome": "Fernando Leite",
    "prioridade": "Alta",
    "diasAberto": 10,
    "probabilidade": "40%",
    "proximaAcao": "Contactar o cliente para confirmar se recebeu a proposta",
    "proximoContacto": "20/07/2026",
    "observacoes": "Enviamos a proposta mas o cliente não deu feedback",
    "classeCliente": "C",
    "crmStatus": "Aberto",
    "dataEnvio": "13/07/2026"
  },
  {
    "id": "d_sf_63",
    "semana": "Semana Finda",
    "clienteNome": "BAXTTER",
    "titulo": "Impressão de Flyers",
    "valor": 444600,
    "valorAprovado": 444600,
    "valorPerdido": 0,
    "etapa": "fechado",
    "comercialId": "u3",
    "comercialNome": "Fernando Leite",
    "prioridade": "Normal",
    "diasAberto": 8,
    "probabilidade": "100%",
    "proximaAcao": "Levantamento do material no fornecedor entrega ao cliente",
    "proximoContacto": "20/07/2026",
    "observacoes": "O material está pronto para ser entregue",
    "classeCliente": "C",
    "crmStatus": "Fechado ganho",
    "dataEnvio": "15/07/2026"
  }
];

export const initialGuidelines: Guideline[] = [
  {
    "id": 1,
    "acao": "Acompanhamento Semanal FILDA",
    "criterio": "Propostas da Semana Finda (13 - 17 Julho 2026)",
    "proximoPasso": "Acompanhar adjudicações e entregas para o certame",
    "chipClass": "chip-error"
  },
  {
    "id": 2,
    "acao": "Negociação Prioritária UNITEL & SIAC",
    "criterio": "Propostas com valores elevados (> 25M AOA)",
    "proximoPasso": "Marcar reunião executiva com os decisores das marcas",
    "chipClass": "chip-warning"
  },
  {
    "id": 3,
    "acao": "Produção e Entregas em Curso",
    "criterio": "Processos aprovados (ZAP, Carpinangola, Cegid, Sonangol)",
    "proximoPasso": "Garantir expedição no prazo e emissão da fatura",
    "chipClass": "chip-success"
  },
  {
    "id": 4,
    "acao": "Desempenho Comercial",
    "criterio": "Comerciais com fecho superior à meta semanal",
    "proximoPasso": "Reforçar prospeção e agendamento de novas visitas",
    "chipClass": "chip-primary"
  }
];

export const initialNotifications: NotificationItem[] = [
  {
    "id": 1,
    "type": "success",
    "title": "Sonangol P&P Aprovada — 7.9M AOA",
    "text": "Ilídio Pedro atingiu 317% da sua meta semanal! 🏆"
  },
  {
    "id": 2,
    "type": "success",
    "title": "Viação e Trânsito Aprovada — 7.2M AOA",
    "text": "Marta de Oliveira atingiu 117% da sua meta semanal!"
  },
  {
    "id": 3,
    "type": "info",
    "title": "Grande Oportunidade UNITEL — 96.1M AOA",
    "text": "Luísa Baltazar em negociação para canecas e garrafas térmicas."
  },
  {
    "id": 4,
    "type": "warn",
    "title": "Acompanhamento SIAC — 29.6M AOA",
    "text": "Totens em Betão aguardam validação de reunião."
  }
];

export const initialActivityFeed: ActivityFeed[] = [
  {
    "type": "deal",
    "text": "Luísa Baltazar registou proposta UNITEL de 96.1M AOA",
    "time": "Há 15 minutos"
  },
  {
    "type": "deal",
    "text": "Sonangol P&P aprovou proposta de 7.9M AOA com Ilídio Pedro",
    "time": "Há 1 hora"
  },
  {
    "type": "visit",
    "text": "Marta de Oliveira realizou visita comercial na Nossa Seguros",
    "time": "Há 2 horas"
  },
  {
    "type": "client",
    "text": "Novo registo da empresa Cegid/Primavera no sistema",
    "time": "Hoje"
  }
];

export function loadFromLocalStorage<T>(key: string, defaultValue: T): T {
  try {
    const item = localStorage.getItem(key);
    return item ? JSON.parse(item) : defaultValue;
  } catch {
    return defaultValue;
  }
}

export function saveToLocalStorage<T>(key: string, value: T): void {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch (e) {
    console.error("Error saving to localStorage", e);
  }
}

export const initialRelatoriosDiarios = [
  {
    id: "RD-2026-07-22",
    data: "2026-07-22",
    semana: "Semana 30 (21 a 25 de Julho de 2026)",
    comercialNome: "David Neto / Equipa GPA Angola",
    criadoEm: "2026-07-22T20:00:00.000Z",
    actividadeEquipa: [
      {
        comercialNome: "Luísa Baltazar",
        resumo: "Elaboração e envio de proposta à Unitel (Capas de Documentos). Conclusão do trabalho da Unitel (5.000.000 de folhas timbradas). Análise de propostas emitidas (Access Bank, DP World, Automatriz). Alinhamento para FILDA (23-24 de Julho). Conclusão da proposta da Endiama (Revista Interna)."
      },
      {
        comercialNome: "Amélia Cassinda",
        resumo: "Trabalho de campo: Levantamento de sacos no BCGA; Entrega de material na Endiama (Lanternas); Amostra reprovada na SBM Offshore (Posters). 3 Propostas enviadas: Clínica Sagrada Esperança (Vinil Fosco - 3.485.030,16 Kz), Sonils (Quadros em Acrílico - 62.061.600,00 Kz), AGT (Livros - 50.074.500,00 Kz)."
      },
      {
        comercialNome: "Marta de Oliveira",
        resumo: "Visita à Gráfica Yuri devido à reclamação da roleta da Gemcorp com defeito. Feedback dos orçamentos enviados (ATO, Angoalissar, Africana) - foco na FILDA. Canalização de concursos públicos (Viaturas)."
      },
      {
        comercialNome: "David Guedes",
        resumo: "Solicitação de feedback das propostas enviadas (DP World e Access Bank). Elaboração e atualização de propostas (Automatriz, Access Bank, Peixe Fresco, DP World)."
      },
      {
        comercialNome: "Carlos Francisco",
        resumo: "Trabalho de campo acompanhando a Sra. Amélia Cassinda (BCGA, Endiama e SBM Offshore). Contacto com Soluções Gráficas - orçamento em análise."
      },
      {
        comercialNome: "Ilídio Pedro",
        resumo: "Trabalho de campo: Entrega de material na Sonangol e Gemcorp; Auxílio ao Sr. José Neto no caso Nestlé (Canetas Sublimaxi); Visita à Nestlé (Sacolas); Reclamação na Gráfica Express."
      }
    ],
    pipelineTotal: 167610132.48,
    pipelineDestaques: [
      { cliente: "AGT", valor: 50074500.00, descricao: "Livros em Produção/Aprovação" },
      { cliente: "SONILS", valor: 62061600.00, descricao: "Caixas Leds e Sinalética em Acrílico" },
      { cliente: "AUTOMATRIZ", valor: 28706340.00, descricao: "Flybanners, Vinis e Letreiro Luminoso" },
      { cliente: "DP WORLD", valor: 14774400.00, descricao: "Quadros em Acrílico" }
    ],
    visitasRealizadas: [
      { cliente: "Sonangol", descricao: "Entrega de material promocional" },
      { cliente: "SBM Offshore", descricao: "Apresentação de amostras de posters (necessita revisão)" },
      { cliente: "Nestlé", descricao: "Acompanhamento sacolas e canetas sublimaxi" },
      { cliente: "ENDIAMA", descricao: "Entrega de lanternas e alinhamento revista interna" },
      { cliente: "Imbono", descricao: "Prospeção e acompanhamento comercial" }
    ],
    propostasEmitidasCount: 13,
    propostasEmitidasValorTotal: 167610132.48,
    propostasEmitidasDestaques: [
      { cliente: "ACCESS BANK", valor: 5176740.00, descricao: "Blocos de notas, Fitas de pescoço, Canetas metalizadas" },
      { cliente: "Clínica Sagrada Esperança", valor: 3485030.16, descricao: "Vinil Fosco personalizado" },
      { cliente: "DP WORLD", valor: 14774400.00, descricao: "Quadros em Acrílico e Comunicação Visual" }
    ],
    adjudicacoesCount: 0,
    cobrancasEfectuadas: "Sem diligências de cobrança pendentes na área financeira no dia 22 de Julho de 2026.",
    observacoes: "Dia marcado por forte atividade de campo, acompanhamento da FILDA e submissão de propostas de alto valor na AGT e SONILS."
  }
];

export const initialHistoricoSemanas = [
  {
    id: "SEM-2026-W28",
    rotuloSemana: "06–10 Jul 2026",
    mes: "Julho 2026",
    propostas: 29,
    valorTotal: 150282285.88,
    valorAprovado: 19914950.00,
    valorPerdido: 11779700.00,
    forecast: 76353142.04,
    conversao: "13,2%",
    ticketMedio: 5182147.79,
    visitasTotal: 18,
    dataCompilacao: "2026-07-10T20:00:00.000Z",
    autoCompiladoSexta: true
  },
  {
    id: "SEM-2026-W29",
    rotuloSemana: "13–17 Jul 2026",
    mes: "Julho 2026",
    propostas: 32,
    valorTotal: 263450431.50,
    valorAprovado: 26762350.00,
    valorPerdido: 11712075.00,
    forecast: 123115722.45,
    conversao: "10,2%",
    ticketMedio: 8232825.98,
    visitasTotal: 24,
    dataCompilacao: "2026-07-17T20:00:00.000Z",
    autoCompiladoSexta: true
  },
  {
    id: "SEM-2026-W30",
    rotuloSemana: "20–25 Jul 2026",
    mes: "Julho 2026",
    propostas: 13,
    valorTotal: 167610132.48,
    valorAprovado: 0.00,
    valorPerdido: 0.00,
    forecast: 67044052.99,
    conversao: "0,0%",
    ticketMedio: 12893087.11,
    visitasTotal: 5,
    dataCompilacao: "2026-07-22T20:00:00.000Z",
    autoCompiladoSexta: false
  },
  {
    id: "SEM-2026-W31",
    rotuloSemana: "27–31 Jul 2026",
    mes: "Julho 2026",
    propostas: 0,
    valorTotal: 0,
    valorAprovado: 0,
    valorPerdido: 0,
    forecast: 0,
    conversao: "—",
    ticketMedio: 0,
    visitasTotal: 0,
    dataCompilacao: "Aguardando Trabalhos (27 a 31 Jul)",
    autoCompiladoSexta: false
  }
];

export const initialHistoricoMeses = [
  {
    id: "MES-2026-05",
    mes: "Maio 2026",
    totalPropostas: 0,
    valorPropostoTotal: 0,
    valorAprovadoTotal: 0,
    valorPerdidoTotal: 0,
    pipelineAberto: 0,
    forecast: 0,
    conversaoMedia: "—",
    semanasIncluidas: ["Semana 18", "Semana 19", "Semana 20", "Semana 21"],
    geradoPorAdmin: "Aguardando Preenchimento",
    dataGeracao: "2026-05-31T20:00:00.000Z"
  },
  {
    id: "MES-2026-06",
    mes: "Junho 2026",
    totalPropostas: 98,
    valorPropostoTotal: 485000000.00,
    valorAprovadoTotal: 62400000.00,
    valorPerdidoTotal: 28500000.00,
    pipelineAberto: 198000000.00,
    forecast: 115000000.00,
    conversaoMedia: "12,8%",
    semanasIncluidas: ["Semana 23", "Semana 24", "Semana 25", "Semana 26"],
    geradoPorAdmin: "David Neto",
    dataGeracao: "2026-06-30T19:30:00.000Z"
  },
  {
    id: "MES-2026-07",
    mes: "Julho 2026",
    totalPropostas: 127,
    valorPropostoTotal: 888350863.86,
    valorAprovadoTotal: 105177300.00,
    valorPerdidoTotal: 31950550.00,
    pipelineAberto: 224976007.00,
    forecast: 345268864.49,
    conversaoMedia: "11,8%",
    semanasIncluidas: ["06–10 Jul 2026", "13–17 Jul 2026", "20–25 Jul 2026", "27–31 Jul 2026"],
    geradoPorAdmin: "David Neto",
    dataGeracao: "2026-07-27T10:00:00.000Z"
  },
  {
    id: "MES-2026-08",
    mes: "Agosto 2026",
    totalPropostas: 0,
    valorPropostoTotal: 0,
    valorAprovadoTotal: 0,
    valorPerdidoTotal: 0,
    pipelineAberto: 0,
    forecast: 0,
    conversaoMedia: "—",
    semanasIncluidas: ["03–07 Ago 2026", "10–14 Ago 2026", "17–21 Ago 2026", "24–28 Ago 2026"],
    geradoPorAdmin: "Aguardando Preenchimento",
    dataGeracao: "Aguardando Preenchimento"
  }
];

